### ISSUE TITLE
Add minimum lenght filter to mediathek listing

### ISSUE THREAD

**Issue by lebochequirit** [mediathekview/zapp#104]
TV stations tend to split some news shows into single stories and publish them to the Web.
That leads to listings bloated by entries like "Verwirrung nach schwerem Unfall", 1m 25s.

An idea would be a slider in settings that allows to set a minimum length for Mediathek entries.

What do you think?

L.B.Q.R.

P.S.: Even with bloated listings, Zapp changed my tv watching life. It is very handy as a feeding remote to Kodi. Thank you.

**Comment by cemrich** [comment]
I would like to have this feature myself, but the MediathekViewWeb-API is currently unable to filter by duration. Maybe I can implement this as soon as @bagbag releases version 2 of his API.

I would love a UI where the user can filter by different "duration slots", eg. "very short", "about half an hour", "about an hour" an "movie length". This way it would be very easy to filter for long movies, not so long documentations, rather short kids shows and very short teasers or news snippets.

**Comment by bagbag** [comment]
Ops, I accidently had this project on "Ignoring".

The server parts concerning searching are more or less finsihed, if you want to start testing the API (and may even implement and release it - if it proves to be stable) just leave me a mail.
This would also close #106.

**Comment by dennmuel** [comment]
Duration would be a quite handy search filter. What do you think about others like the channel or publication date? (Should I open a separate issue for that?)

**Comment by cemrich** [comment]
@dennmuel At this time filtering cannot be implemented anyway. I'll review all issues tagged with mvw-api-2.0 (including) comments and make a concept when the time comes.

**Comment by HeadCrash66** [comment]
Hi,

I love and enjoy your app much.

I have seen that at MediathekViewWeb it is possible to use advanced search syntax. But it looks like this is not working in the app.
Would be really helpful if it would be possible to use this filters in the zapp app. too.

May thanks.

**Comment by cemrich** [comment]
> I have seen that at MediathekViewWeb it is possible to use advanced search syntax. But it looks like this is not working in the app.
> Would be really helpful if it would be possible to use this filters in the zapp app too.

Thank you for your feedback! I know Zapp needs a filter badly. This is on top of my priority list. However, I will not implement the search syntax of MediathekViewWeb as it not as self-explanatory as I would like it to be in Zapp.

**Comment by cemrich** [comment]
Fixed in 6.0.0
