### ISSUE TITLE
Blacklist tv stations in mediathek view

### ISSUE THREAD

**Issue by lebochequirit** [mediathekview/zapp#105]
I have a few stations I never watch (arte.fr, for example - sad enough). Guess I'm not alone with that.
Filtering those stations in the Mediathek listing and the live screen would add to the usability.

**Comment by cemrich** [comment]
I will exclude non-German channels like arte.fr and provide a more complex filter interface as soon as the MediathekViewWeb-Api does allow it. 

The live screen does provide a sorting feature where you can sort unused channels to the end of the list (through settings). For hiding channels there is already a ticket: #9

**Comment by cemrich** [comment]
A quick update: 
Hiding channels in live view is already implemented (#9). Also I excluded ARTE.FR completely for the next release.

**Comment by SebiderSushi** [comment]
Is there any user-accessible way to re-include ARTE.FR?
Will there be one once the MediathekView tab has a user-facing interface which allows controlling the filter?

**Comment by cemrich** [comment]
> Is there any user-accessible way to re-include ARTE.FR?

No, I am sorry, but there will be no way to include ARTE.FR. I realize that the removal of features is always hurtful to a minority of users. But Zapp is designed for a German speaking or German learning audience and ARTE.FR (or an option to enable it) will be clutter for the vast majority of Zapp users.

**Comment by SebiderSushi** [comment]
Thank you for your answer.

**Comment by cemrich** [comment]
Fixed in 6.0.0
