### ISSUE TITLE
pink banner, rosafarbene Meldung am unteren Bildrand

### ISSUE THREAD

**Issue by deejay73** [mediathekview/zapp#142]
Der rosafarbene Banner in der Mediathek am unteren Bildrand sagt: "Das Video konnte nicht geladen werden. Vielleicht besteht keine Internet-Verbindung oder das Video ist in deinem Land nicht verfügbar."

Die Meldung ist ja grundsätzlich richtig. Doch: Das Video läuft weiter!
Auch wenn der Empfang nicht besonders gut ist läuft die App ansonsten störungsfrei.
Nur der rosa Balken, der bleibt leider.

Wäre es denn möglich, dass der Balken automatisch wieder verschwindet, wenn das Video, so wie in allen meinen Fällen, weiterläuft? Alternativ könnte ja auch ein kleines "x" zum Schließen der Meldung vorhanden sein. Oder einfach zur Seite wischen, so wie man ne e-Mail löscht?!?

Schade, denn so muß ich einen Film, der grad mal 45 Minuten läuft, bestimmt 4x neu starten, um dann jedes mal an die zuletzt gesehene Stelle vorzuspulen...

**Comment by cemrich** [comment]
Danke für den Vorschlag!

**Comment by deejay73** [comment]
Auch bei Version 2.2.2 immernoch Meldungen, die sich nicht wegklicken lassen.
Sowohl in der Mediathek, als auch "live".
Die Meldungen erscheinen, wenn das WLan kurz unterbricht oder der Empfang
vorübergehend etwas schlechter wird. Unterdessen läuft der Film weiter als wär nix gewesen,
nur die Meldung bleibt beharrlich am unteren Bildrand und nervt. 

+ Abhilfe Mediathek: Film stoppen und neu starten, anschliessend vorspulen,
   bis man wieder an der Stelle ist, an der man unfreiwillig abbrechen musste.

+ Abhilfe live TV: Umschalten auf anderes Programm und wieder zurückschalten.

Ist denn schon eine Lösung des Problems in Aussicht?

**Comment by cemrich** [comment]
Hallo @deejay73,

ich kann verstehen, dass du frustriert bist, wenn ein Programm nicht so funktioniert, wie du es dir wünschst. Ich entwickele das Frontend von Zapp allerdings so gut wie alleine - als berufstätige Mutter, unbezahlt in meiner doch sehr begrenzten Freizeit. Ich kann Bugs und Feature-Requests in Zapp also nur sehr langsam und eher sporadisch abarbeiten. Außerdem haben Sicherheitsfixes und Crashes natürlich immer Vorrang.

Zu erkennen, ob ein Video gerade hängt, der Stream komplett abgerissen ist oder einfach nur die Internetverbindung einen Schluckauf hat, ist keine ganz einfache Aufgabe. Dazu muss die Erkennung ja auch über alle unterstützten Android-Versionen hinweg (gleich gut) funktionieren und getestet werden und darf keine andere Funktionalität von Zapp kaputt machen. 

Falls dir die Entwicklung von Zapp nicht schnell genug geht, kannst du dich gerne selbst an diesem Ticket versuchen - Zapp ist Open-Source und ich nehme saubere und funktionierende [Pull-Requests](https://help.github.com/en/articles/about-pull-requests) gerne an. Alternativ kannst du dir einen anderen Android-Entwickler suchen, der dieses Feature bezahlt oder unbezahlt fixt und einen Pull-Request stellt.

**Comment by rugk** [comment]
Als alternative Lösung: Wäre es nicht mgl. den Banner "wegklickbar" zu machen, also einfach zum schließen? Denke, das würde das Problem des OP schon beheben.

**Comment by cemrich** [comment]
@rugk: Nein, weil der Player sich momentan bei einer Fehlermeldung in einem Stand befinden kann, in dem er nicht mehr gestartet werden kann. Das weg klicken könnte also beim nächsten Abspielversuch die App crashen.

Mir fällt schon was ein.

**Comment by cemrich** [comment]
Das Banner hat mit Version 3.0.0 einen Retry-Button.

**Comment by deejay73** [comment]
Danke, funktioniert prima!
________________________________
Von: cemrich <notifications@github.com>
Gesendet: Mittwoch, 17. Juli 2019 21:31
An: mediathekview/zapp <zapp@noreply.github.com>
Cc: deejay73 <dirk_junker@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [mediathekview/zapp] pink banner, rosafarbene Meldung am unteren Bildrand (#142)


Das Banner hat mit Version 3.0.0 einen Retry-Button.
