### ISSUE TITLE
Video favourit button

### ISSUE THREAD

**Issue by sandoxy** [mediathekview/zapp#143]
Such a button would be great, to easy find videos, to continue watching:)

**Comment by cemrich** [comment]
I would love this feature, but I need version 2 of the mediathekviewweb API to be released before I am able to implement this. Maybe @bagbag can give some status update / estimate / maintainer status?

**Comment by cemrich** [comment]
There is now a way to implement this based upon the current code base. This feature will be one of the next steps down the road.

**Comment by cemrich** [comment]
This issue is fixed with version 8.0.0
