### ISSUE TITLE
Picture in picture mode

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#155]
https://developer.android.com/guide/topics/ui/picture-in-picture

**Comment by cemrich** [comment]
This was fixed in v3.0.0

**Comment by SebiderSushi** [comment]
But the native PiP from oreo and above is not resizable, right?

**Comment by cemrich** [comment]
@SebiderSushi On my system (Android P) PiP can have two different sizes. Furthermore Zapp does use resizeable activities and can be used side by side with other apps (if the system does support this feature).
