### ISSUE TITLE
Unexpected behavior about navigation drawer

### ISSUE THREAD

**Issue by arthur-star** [mediathekview/zapp#166]
## steps to reproduce

Set system navigation method as Three-key navigation.

1. Press navigation button on the top left of the screen
2. Open the navigation drawer

<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/62507829-25996500-b838-11e9-9e7d-5e96b68d8e06.png" width="50%" height="50%">
</div>

3. Press the system **BACK** button
4. Quit the Zapp (Unexpected behavior)

## expected result

- Just close the navigation drawer, do not close the app

## observed behavior

- Quit the Zapp (Unexpected behavior)

## versions

```
Hardware: HUAWEI MATE 10
Version 3.0.0 (35)
```

**Comment by cemrich** [comment]
Thank you for your feedback! Using PlayStore and Google Maps as UX reference I'll implement this behavior :)

**Comment by cemrich** [comment]
This issue will be fixed in 3.2.0

**Comment by arthur-star** [comment]
Thanks for your response
