### ISSUE TITLE
Phoenix funktioniert nicht mehr

### ISSUE THREAD

**Issue by deejay73** [mediathekview/zapp#167]
Phoenix funktioniert nicht mehr

**Comment by cemrich** [comment]
@deejay73 Auf meinem Gerät funktioniert Phönix einwandfrei. Kannst du es bitte noch einmal mit der neusten Version 3.2.0 versuchen?

**Comment by deejay73** [comment]
Habe die neueste Version 3.2.0 installiert.
Auf mehreren Handys mit diversen Android-Versionen und verschiedenen WLan's funktioniert jeweils alles, ausser Phoenix.
Extra nochmal ausprobiert...

________________________________
Von: cemrich <notifications@github.com>
Gesendet: Samstag, 10. August 2019 18:30
An: mediathekview/zapp <zapp@noreply.github.com>
Cc: deejay73 <dirk_junker@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [mediathekview/zapp] Phoenix funktioniert nicht mehr (#167)


@deejay73<https://github.com/deejay73> Auf meinem Gerät funktioniert Phönix einwandfrei. Kannst du es bitte noch einmal mit der neusten Version 3.2.0 versuchen?

**Comment by cemrich** [comment]
Mein Fehler! Nach dem kompletten Neustart von Zapp sollte Phönix jetzt wieder laufen.

**Comment by deejay73** [comment]
läuft!👍
________________________________
Von: cemrich <notifications@github.com>
Gesendet: Sonntag, 11. August 2019 20:00
An: mediathekview/zapp <zapp@noreply.github.com>
Cc: deejay73 <dirk_junker@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [mediathekview/zapp] Phoenix funktioniert nicht mehr (#167)


Mein Fehler! Nach dem kompletten Neustart von Zapp sollte Phönix jetzt wieder laufen.
