### ISSUE TITLE
Mark visually which films are already downloaded

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#170]
It's similar to [issue 144](https://github.com/mediathekview/zapp/issues/144) but instead of having a dedicated list of downloaded videos (which would be nice as well though) I would propose just to have a mark or highlight on already downloaded videos / records.

**Comment by cemrich** [comment]
This would require to save ids of downloaded shows into a database and would most likely result in a performance hit when loading the show list. Furthermore a very clear UI is required for this feature to work (e.g. mark which quality has been downloaded, check if downloaded file is still present, etc.).

I'll keep this issue, but don't expect it to be resolved any time soon.

**Comment by alexanderadam** [comment]
> and would most likely result in a performance hit when loading the show list

Can you elaborate this? The way I imagine this, is that the list of downloaded videos could be queried separately and querying the list shouldn't be slow, right? Also I guess that there should be an internal ID of every entry shown so there should'n be much more logic than 'is this id in the list of known, downloaded videos that we just queried'.

> Furthermore a very clear UI is required for this feature to work (e.g. mark which quality has been downloaded, check if downloaded file is still present, etc.).

I agree with that. The use case (at least for me) would be to see whether I downloaded/saw something already. So I wouldn't care about the quality or presence. A checkmark (or a badge with a text 'downloaded') besides the title would do (for me).
Marking a video manually as downloaded/seen would also work for me but I guess it's easier for everyone if this would happen automatically.

> I'll keep this issue

Thank you :+1:

**Comment by cemrich** [comment]
> The way I imagine this, is that the list of downloaded videos could be queried separately and querying the list shouldn't be slow, right (I agree that you might need a database for that though)?
Also I guess that there should be an internal ID of every entry shown so there should'n be much more logic than 'is this id in the list of known, downloaded videos that we just queried'.
I would have to query the downloads database for every entry inside the (visible) mediathek show list, which may change rapidly during scrolling or filtering.

On the other hand, viewing progress could be saved inside the same table or database. So this change would fix two issues. 

I am a bit reluctant to introduce a database infrastructure into zapp before switching to v2 of the mediathekview api. Most likely the shows ids and some of the metadata structure will change with the switch.

**Comment by cemrich** [comment]
Quick update: I have to introduce a database to fix #117 so this feature (or something similar) will come :-)

**Comment by cemrich** [comment]
I just [released a beta version](https://github.com/mediathekview/zapp/releases/tag/v3.5.0-beta.1) to test this feature on a wide variety of devices. To install you have to uninstall any Zapp version from F-Droid first. Please let me know if you experience any issues!

**Comment by alexanderadam** [comment]
It is working great! I like the preview image. This is a wonderful release. :heart:
