### ISSUE TITLE
Register Zapp for video urls inside Mediathek websites

### ISSUE THREAD

**Issue by dadosch** [mediathekview/zapp#171]
to view the corresponding Mediathek video.

**Comment by cemrich** [comment]
I don't this this can be done. We don't know every url scheme of every mediathek website, so Zapp can't register beforehand for deeplinks. Even if it could, Zapp would need to query the api for a show with a specific mediathek url. This can't be done with v1 of the api.

Any thoughts?

**Comment by rugk** [comment]
Do you, @dadosch, just want to have Zapp being opened when we go to https://www.ardmediathek.de/? Or only when we go to https://www.ardmediathek.de//specific_video_url_here?

**Comment by dadosch** [comment]
The second one. Reason was I stumbled across a link in social media to the Mediathek and their HTML player is really laggy and doesn't work very well on mobile devices. (Additionally you apparently can't download some videos from the Mediathek from the html Website) You can search for the title in Zapp, but that's unconvinient and Interrupts the viewing action.

**Comment by cemrich** [comment]
I won't implement this. I am not sure it can be done but either way it is to much work for such a small feature.
