### ISSUE TITLE
Mediathek-Download-Buttons are broken/misleading in some cases?

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#173]
I'm not quite sure what is expected here.

See this example for [the show `Einstein`](https://www.srf.ch/play/tv/einstein/video/die-neue-kristallkugel-vorhersagen-im-digitalen-zeitalter?id=50588a4a-3f74-4b60-b5ee-a5f571b5d028) for instance:

![Screenshot_20191011-121547_Zapp](https://user-images.githubusercontent.com/372620/66653484-76fb1180-ec38-11e9-8955-453383e749ae.jpg)

The share buttons right of `High`, `Medium` and `Low` give the video player selection in my case and I can open it with VLC for example.
The "download" icon on the right of `ST` downloads a `….ttml` file that I cannot open at all.

So I guess _something_ is broken or at least misleading here.

PS: the content could be geofenced obviously. I just saw it on this video though and decided finally to also open an issue for that.

**Comment by cemrich** [comment]
This show cannot be downloaded (at least not easily) because it is not served as .mp4 but as stream. Therefore there are no download buttons. The UI is misleading here. The download buttons should be disabled instead of hidden and maybe an error message shown.

**Comment by cemrich** [comment]
This improvement will be part of the next release (without the typo): 
![Screenshot_20191103-142403_Zapp](https://user-images.githubusercontent.com/403202/68085894-239a6e80-fe46-11e9-915d-67a4f1606320.png)

**Comment by cemrich** [comment]
This issue is fixed in v3.3.0, which will hit F-Droid in a few days. Please reopen this issue if you find any problems.
