### ISSUE TITLE
Add radio stations

### ISSUE THREAD

**Issue by dennmuel** [mediathekview/zapp#175]
Would it be considerable to add public radio stations (like DLF, SWR etc. and their variations) and/or their "Audiotheken" (hoerspielundfeature.de, ardaudiothek.de)? Feels like asking a little bit too much, so I'm fine, if this is just not in the scope of this app.

**Comment by cemrich** [comment]
I already thought about it, but sadly this feature is out of scope. Thanks for the suggestion though!
