### ISSUE TITLE
Probleme mit ARD-Stream

### ISSUE THREAD

**Issue by jw243** [mediathekview/zapp#182]
Seit etwa 2 Wochen habe ich Probleme mit dem ARD-Stream. Wenn ich ihn auswähle, sucht er nach dem Stream, aber kann ihn nie öffnen.

Ein Öffnen ist nur möglich, wenn ich zunächst einen anderen Stream auswähle (z.B. ZDF) und dann durch Wischen auf den ARD-Stream wechsele.

Der Stream ist dann jedoch nicht stabil. Immer wieder hängt er sich auf und ich muss erneut den Sender durch Wischen wechseln und dann zur ARD zurückwechseln.

Würde mich sehr freuen, wenn der ARD-Stream wieder stabil laufen würde.

Vielen Dank!

**Comment by cemrich** [comment]
Ich schaue mir das Problem mal an, kann aber nichts versprechen.

Hat noch jemand Probleme mit dem Stream? Macht der Stream auf der [Website ](https://live.daserste.de/) die gleichen Probleme?

**Comment by jw243** [comment]
Das Problem besteht nach wie vor. Der Stream startet meist nicht und läuft extrem instabil.
Im Browser direkt auf der ARD-Homepage startet der Stream auf dem gleichen Gerät sofort und läuft absolut stabil. Ich habe dies mehrmals ausprobiert.
Würde mich sehr freuen, wenn sich eine Lösung für das Problem finden würde.
Vielen Dank!

**Comment by cemrich** [comment]
Ich habe die Streamadresse geändert. Er sollte jetzt stabiler laufen - wenn nicht, gerne das Ticket noch mal öffnen.
