### ISSUE TITLE
Some movies show "Online since" 01.01.1970

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#184]
For example: [`Alles Wissen - Verbrechen mit künstlicher Intelligenz`](https://www.hr-fernsehen.de/sendungen-a-z/alles-wissen/sendungen/alles-wissen---verbrechen-mit-kuenstlicher-intelligenz-,sendung-44096.html).

The show was published in 2018 and probably not coincidentally at the Unix epoch date. :wink:

**Comment by cemrich** [comment]
Thanks for reporting!

**Comment by cemrich** [comment]
This issue should be fixed in release [v3.4.0](https://github.com/mediathekview/zapp/releases/tag/v3.4.0) which should hit F-Droid the next few days.
