### ISSUE TITLE
Works on Fire TV, but the mediathek search is not usable

### ISSUE THREAD

**Issue by Retch** [mediathekview/zapp#186]
Livestreaming works great, nice app. But the search in the mediathek view can't be used because the onscreen keyboard is not opening.

**Comment by cemrich** [comment]
Which version of Zapp are you using?

I have no access to a fire tv, so I won't be able to fix this issue, but maybe other people might be able to help.

**Comment by Retch** [comment]
I’m using the newest version everytime.

**Comment by cemrich** [comment]
> I’m using the newest version everytime.
Are you sideloading the app or using any app store?

**Comment by Retch** [comment]
I'm sideloading the apk.

**Comment by cemrich** [comment]
I'll see if I can reproduce this issue on some sort of emulator.

**Comment by cemrich** [comment]
I was able to reproduce this on an Android TV emulator. Fixed with help of this thread: https://stackoverflow.com/questions/12022715/unable-to-show-keyboard-automatically-in-the-searchview

**Comment by Retch** [comment]
> I was able to reproduce this on an Android TV emulator. Fixed with help of this thread: https://stackoverflow.com/questions/12022715/unable-to-show-keyboard-automatically-in-the-searchview

Will try it, thank you very much!
