### ISSUE TITLE
Kika Livestream URL incorrect

### ISSUE THREAD

**Issue by matthias-vorwerk** [mediathekview/zapp#190]
For some time now the KIKA livestream is broken. The used URL in zapp/blob/master/app/src/main/res/raw/channels.json (https://kikade-lh.akamaihd.net/i/livetvkika_de@450035/master.m3u8) just shows some static movie.

Referring to https://wiki.ubuntuusers.de/Internet-TV/Stationen/ probably the URL
https://kikageohls-i.akamaihd.net/hls/live/1006268/livetvkika_de/master.m3u8
could be used.

**Comment by cemrich** [comment]
Thank you very much for reporting! You can restart Zapp now and it will use the correct stream url.
