### ISSUE TITLE
Switch to new Zapp-Backend address

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#192]
https://api.zapp.wiegandt.eu/v1/

**Comment by alex1702** [comment]
Würde noch die Domain auf eine MediathekView Domain ändern.

**Comment by cemrich** [comment]
@Nicklas2751 Können wir das machen? Dann ist es komplett sauber und zukunftssicher.

**Comment by Nicklas2751** [comment]
Klar

**Comment by Nicklas2751** [comment]
https://api.zapp.mediathekview.de/
