### ISSUE TITLE
Make Zapp resizable

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#195]
Yes, it's me again. I'm so sorry!

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and the application is always nearly squarish:

![Screenshot of Zapp on Samsung DeX](https://user-images.githubusercontent.com/372620/88277863-b5525080-cce1-11ea-9ccd-2b983b6ad2ab.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.
**PPS:** I'm not sure whether this is relevant but [this](https://codeberg.org/gitnex/GitNex/pulls/601/files) is how GitNex fixed the issue and [this](https://github.com/TobiGr/NewPipe/commit/ea486e769ff9728c4e5d7dac6028587c39476fa9) is how NewPipe fixed it. Both are now also resizable with dragging border and corners.

**Comment by cemrich** [comment]
I just [released a beta version](https://github.com/mediathekview/zapp/releases/tag/v3.5.0-beta.1) to test this feature on a wide variety of devices. To install it, you have to uninstall any Zapp version from F-Droid first. Please let me know if you experience any issues!

**Comment by alexanderadam** [comment]
This feature is working great! Thank you so much! :heart:

**Comment by cemrich** [comment]
Thanks for testing!

**Comment by alexanderadam** [comment]
Thank _you_ for maintaining Zapp! :+1:
