### ISSUE TITLE
Add Austrian channels

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#2]

**Comment by rugk** [comment]
As for https://github.com/cemrich/zapp/issues/1 and this issue I think a filter would be useful, as only few people are travellers between these countries and the majority of all others likely won't want to watch "foreign" channels.

**Comment by cemrich** [comment]
http://www.srf.ch/livestream/player/srf-info is geoblocked in Germany. Otherwise the channels should work fine.

**Comment by DJCrashdummy** [comment]
@cemrich i guess your last comment here and at #1 got a little bit mixed... :wink: 

referencing to https://github.com/cemrich/zapp/issues/1#issuecomment-282855018 ORF (https://tvthek.orf.at/live) no longer uses flash. finally they use HTML5 with the following playlists/URLs (example for ORF Sport):

320x180:	https://orfs.cdn.ors.at/out/u/orfs/q1a/manifest.m3u8
512x288:	https://orfs.cdn.ors.at/out/u/orfs/qxb/manifest.m3u8
640x360:	https://orfs.cdn.ors.at/out/u/orfs/q4a/manifest.m3u8
960x540:	https://orfs.cdn.ors.at/out/u/orfs/q6a/manifest.m3u8
1280x720:	https://orfs.cdn.ors.at/out/u/orfs/q8c/manifest.m3u8

for the other channels substitute `orfs` with `orf1`, `orf2` or `orf3` twice(!) per URL.

hopefully with this information it is possible to include the 4 ORF channels?

**Comment by cemrich** [comment]
More stream addresses: http://www.harryshomepage.de/webtv.html

**Comment by cemrich** [comment]
I'll postpone this issue until streams are no longer geoblocked so I am able to test and Zapps main audience does benefit from this change.

**Comment by ni720** [comment]
@cemrich would it help if i provide you my personal vpn into Austria?
Even if streaming itself is not possible outside Austria, it would still be nice to see the info whats on TV.

**Comment by cemrich** [comment]
> @cemrich would it help if i provide you my personal vpn into Austria?
> Even if streaming itself is not possible outside Austria, it would still be nice to see the info whats on TV.

Yes, that would help. However I am currently not able implement new features (due to pandemic induces free time shortage).

**Comment by ni720** [comment]
ok when ever you have time tell me how to contact you.
