### ISSUE TITLE
Match screen refresh rate with content for smooth playback

### ISSUE THREAD

**Issue by k9janer** [mediathekview/zapp#203]
I'm currently using Zapp on my FireTV to see if it could replace my standard tv cable.

Overall it's working pretty well but one of the major issues I have noticed is that the video stutters every few seconds. The reason is that Zapp doesn't adjust the screen refresh rate (60hz most of the time) to the video stream (50fps in the case of Zapp). 

On newer FireTV you have two options called "Video resolution" and "Match original framerate". Setting the options to "Auto" and "On" respectively uses to 4K 60hz by default but then apps have the opportunity to manage the screen mode themselves.

Some apps like Amazon Prime Video, Kodi and Plex support this to match the screen refresh rate to that of the content being displayed. So a 24 fps movie will be displayed with the tv set to 24hz and 50 fps content with the tv at 50hz. There is an explanation in this article: https://www.aftvnews.com/explanation-of-the-new-frame-rate-matching-feature-on-the-amazon-fire-tv/

Ideally the refresh rate would be matched dynamically to the content but as far as I know all the content you could access in Zapp should be 50 fps and so setting the screen mode to 50hz for the whole app should be sufficient right now.

I'm not a developer and so I don't know how other apps have implemented this but there seems to be some way to achieve this  on a FireTV at least. In addition it looks like with Android 11 there is now an official frame rate API: https://developer.android.com/guide/topics/media/frame-rate

Adding this feature to Zapp would allow for smooth playback just like with the real tv channels on FireTV and it would run much smoother with a 60< hz Display on Android 11+ (like the Pixel 4) as the device could switch to the appropriate refresh rate to minimize/avoid the frame pacing issues.

**Comment by cemrich** [comment]
Wow, this is a deeply technical issue. I will see what I can do to investigate this issue. But I am afraid I can't fix it without an actual Fire TV.

Has anyone experienced similar issues on Android TV / Chromecast?

**Comment by cemrich** [comment]
There seem to be issues with exo player and Fire TV. Amazon recommends using their port of exo player: https://developer.amazon.com/de/docs/fire-tv/media-players.html (which I will most definitely not do).

**Comment by cemrich** [comment]
Kodi seems to use ffmpeg as video player.

**Comment by k9janer** [comment]
Sorry, I did a poor job explaining this issue. This isn't really a bug, it's more of an enhancement.

There is nothing really "broken" about the way Zapp behaves on FireTV.

This just about judder/stutter duo to a mismatch in frame rate/refresh rate. Pretty much all modern displays run at 60hz and so there will always be some stutters when you watch 50hz content on them because there is no way divide the 50 frames evenly across the 60hz.

If you use Zapp on a Smartphone, you will see the same issue if you pay close attention. Some people are more/less susceptible to this. I always notice it with camera movement and it's more noticeable on the big screen.

It seems like some Apps l like Kodi have found a way to adjust the refresh rate on FireTv (and Nvidia Shield) to smoothly display 50hz content and it would be nice to have this in Zapp as well.

**Comment by cemrich** [comment]
Okay, I understand now.

I don't think I can fix this issue though. Zapp uses Googles [ExoPlayer](https://exoplayer.dev/) as video player - which is the de facto standard in Android world. This media player does not seem to adjust frame rate/refresh rate accordingly. This is why most Android apps like ZDF, Zapp, etc. show this behavior. Other apps like Kodi use another video player (most likely ffmpeg, very low level) which avoids this issue.

As Fire TV is not supported by ExoPlayer (I can imagine due to some Google vs. Amazon hostility) and I cannot switch to another video player (because of ease of use, support, updates, etc.) I don't think I can work around this issue.

However, ExoPlayer usually has excellent support for new Android features, so the Android 11 frame rate API you mentioned will most likely be supported in the future.

With that said, I'll close this issue as "won't fix". Nevertheless thank you very much for this detailed report!

**Comment by k9janer** [comment]
Thank you for looking into this. I understand that this is not a priority right now.

For reference I have found the following documentation from Amazon: https://developer.amazon.com/docs/fire-tv/4k-apis-for-hdmi-mode-switch.html

It seems like they created their own implementation for Android 5 but are now using the Android 6+ AOSP implementation. So it looks like FireOS doesn't need any special treatment in this regard.

I'm not a developer but do you think ExoPlayer would have to implement this feature or could Zapp set preferredDisplayModeId on launch/start of playback to a 50hz mode independently and then the video player within the app would run at 50hz as well?

**Comment by cemrich** [comment]
@k9janer This looks line an issue that ExoPlayer should be able to handle. But they state, they don't support FireTV (I would suggest for political reasons). You can always try to open an issue on their bug tracker - but I don't think they will accept it.
