### ISSUE TITLE
Add WDR regional channels

### ISSUE THREAD

**Issue by justf0rfun** [mediathekview/zapp#206]
WDR has several regional studios which contribute with regional journalism to the overall program. The program in each region is almost the same most of the time. One significant exception is "Lokalzeit" which is produced from monday to fryday and broadcasted from 19:30 to 20:00. Lokalzeit does show regional specific content only. So for every region there is a special Lokaluzeit and the broadcasted contents differ. So from 19:30 to 20:00 the users in different regions see different content.

The studios / regions are:

1. Köln
2. Aachen
3. Bielefeld
4. Bonn
5. Dortmund
6. Düsseldorf
7. Duisburg
8. Essen
9. Münster
10. Siegen
11 Wuppertal

I think the Lokalzeit is an important and popular part of regional TV and journalism. Unfortunately there it is not easily accessible for viewers to watch the Lokalzeit for their local region. I think Köln is the default region at least via cable. I am not sure if other regions can be watched via cable. The website does only show one stream, probably Köln, too. Via satellite there are multiple channels for the regions. At some place in program the region which's contents get broadcasted gets switched round robin each week or day. I don't remember when that was. Maybe at the weekend or a repetition in the morning.

The Lokalzeit can be watched via the mediathek but only the next day. Thats fine but can be late for a news show.

Zapp has already two regional channels for SWR. 

Does Zapp only takes the streaming URLs from the Channels websites and configure them in the apps channels JSON file? Or is there some contact to the TV channels? I mean somewhere the stream must come from. Zattoo has all the regional streams so that might be a source of information.

Let's assume Zapp gets those streams maybe it would be a good idea for integration to select just one of them and hide the others. This way the channels list wouldn't get cluttered. This may be achieved by a filter function or by selecting favorites. The same can be used for SWR regional channels or maybe all channels.

**Comment by cemrich** [comment]
Thank you for your feedback!

Local stream urls for wdr are not exposed anywhere - not even on [wdr website](https://www1.wdr.de/)  (Cologne is the default channel). Maybe Zatoo has some kind of contract with WDR and most likely its own streaming server which Zapp cannot use. In addition 11 regional channels would clutter the UI too much.

I am sorry, but I will not implement this feature.

**Comment by WebworkrNet** [comment]
Zattoo does not use the regular stream of the websites belonging to the ARD group.

It is a special case. This is shown by the fact that there are no legal restrictions. All programs are shown that are also regularly sent over the airwaves. On the other hand, ZAPP does not broadcast any programs that are not allowed to be streamed on the internet for legal reasons.

**Comment by WebworkrNet** [comment]
The WDR changes the live stream of the regional studio daily. All programs, whether streamed or not, can be accessed for 7 days via the WDR media library. The WDR invokes the justifiable technical effort not to stream all regional programs.

> [...]

> vielen Dank für Ihr Interesse an unserem Programm.

> Es ist mit einem vertretbaren Aufwand leider technisch nicht möglich, im WDR-Livestream jeder Region "ihre" Lokalzeit zuzuspielen. Deshalb wechseln wir die ausgestrahlte Lokalzeit jeden Tag. Im Anschluss an die Ausstrahlungen sind aber ja alle Lokalzeiten für sieben Tage in der Mediathek abrufbar.

> Mit freundlichen Grüßen

> Ihre Hotline WDR  Fernsehen

**Comment by justf0rfun** [comment]
Do I see this right that you made an inquiry to WDR and that is the answer?

Despite of the sad answer I want to thank you for your work. :)

**Comment by WebworkrNet** [comment]
I also noticed some time ago that the regional stations of the WDR are missing. Before I unnecessarily open a new ticket, I went looking for it and came across this one.

And yes, because I was interested in the background, I asked WDR directly.

**Comment by WebworkrNet** [comment]
@cemrich Would you like to add this to the FAQ?
