### ISSUE TITLE
clone with ads in playstore

### ISSUE THREAD

**Issue by ybrhue** [mediathekview/zapp#207]
https://play.google.com/store/apps/details?id=germanlivestream.germantvlive.germantvlivefree

I know this software is open source, but it is really sad to see, that someone is just stealing the code and added tons of ads. 10k downloads, ad revenue should be at least 3k. Is there any way to take them down?

Sorry for my short issue I am on mobile right now.

**Comment by cemrich** [comment]
Yeah, thanks for reporting. I've seen this and reported it to Google but there is nothing I can do about it. Funny thing is that Google denied Zapp access to the Play Store. But whatever ¯\_(ツ)_/¯
