### ISSUE TITLE
Start behavior as setting

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [mediathekview/zapp#209]
At the moment Zapp always starts with "Live" screen. I mostly use the "Mediathek" screen, though. Maybe it would be good to let the user choose and implement a setting to start either in "Live" or "Mediathek" screen.

**Comment by cemrich** [comment]
Thank you very much for your suggestion!

However, I would like not to clutter the settings screen with more options most users won't use or need. It will get difficult to maintain in the long run and I like to focus on features with a broader impact for all users.
