### ISSUE TITLE
Add screenshots, description, changelog to F-Droid (e.g. by using fastlane)

### ISSUE THREAD

**Issue by jwsp1** [mediathekview/zapp#211]
There are no screenshots, description or changelog n F-Droid. Maybe you'd like to consider using [fastlane](https://fastlane.tools/)?
More here https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ 
and a nice short description here https://gitlab.com/snippets/1895688

**Comment by cemrich** [comment]
Thank you for this hint. I'll look into it :)

**Comment by cemrich** [comment]
This will hopefully be fixed after the next release!

**Comment by jwsp1** [comment]
Awesome!
