### ISSUE TITLE
Sendungsdetails der ARD-Programme seit Zeitumstellung

### ISSUE THREAD

**Issue by jw243** [mediathekview/zapp#214]
Seit der Umstellung auf Winterzeit stimmen die Sendungsdetails bei allen ARD-Programmen (ARD, One, Dritte Programme) nicht mehr. Könnt ihr da was machen oder liegt es an den Sendern?

**Comment by cemrich** [comment]
Danke für den Bugreport! Leider komme ich die nächste Zeit nicht zum Reinschauen, aber das Ticket geht nicht verloren :)

**Comment by cemrich** [comment]
@jw243 Ich kann das Problem nicht reproduzieren. Meinst du die Programminfos für die Live-Streams? Tritt das Problem noch auf?

**Comment by jw243** [comment]
Das Problem tritt nicht mehr auf. Ein oder zwei Wochen nach der Zeitumstellung war das Problem behoben.

Vielen Dank für eure Mühe.

**Comment by cemrich** [comment]
@jw243 Danke für die Rückmeldung!
