### ISSUE TITLE
HR-Stream seit einigen Wochen nur noch ruckelig

### ISSUE THREAD

**Issue by jw243** [mediathekview/zapp#220]
Der Stream des Hessischen Rundfunks läuft seit einiger Zeit nur noch ruckelig. Es gibt keinen flüssigen Film, es ist eher wie eine Aneinanderreihung einzelner Bilder, wie eine zügig abgespielte Diashow. :-(

Für eine Behebung des Fehlers wäre ich sehr dankbar.

**Comment by cemrich** [comment]
Auf meinem Testgerät läuft der Stream flüssig. 

Welches Gerät und welche Android-Version sind denn betroffen?

**Comment by jw243** [comment]
Der HR-Stream läuft nur ruckelfrei, wenn er direkt nach dem Starten der App gestartet wird. Wird der Stream jedoch gestoppt und neu gestartet, oder lief vorher bereits ein anderes Programm, laufen die Bilder ruckelig. Der Ton hingegegen ist nie betroffen.

Ich habe es getestetet auf einem Sony Z3 mit LineageOS 17.1 (Android 10) als auch auf einem Galaxy Tab S2 mit Lineage OS 16.0 (Android 9).

Kannst du dieses Verhalten bestätigen?

**Comment by cemrich** [comment]
LineageOS 17.1 auf dem Poco F1 und Android 7 auf dem Samsung S7 scheinen bei mir keine Probleme zu machen. Ich behalte den Bug aber mal im Auge und versuche weiter, ihn zu reproduzieren.

**Comment by cemrich** [comment]
Da ich den Fehler nicht reproduzieren kann, schließe ich das Ticket. Es darf gerne wieder eröffnet werden, wenn der Fehler noch einmal autritt.
