### ISSUE TITLE
Disable subtitles

### ISSUE THREAD

**Issue by Wiredframe** [mediathekview/zapp#222]
Is there an option to disable the subtitles? Thanks!

**Comment by cemrich** [comment]
You should update to the latest version of Zapp (3.6.1) where a subtitle bug has been fixed. If this does not solve your problem, you have to disable closed captions inside your system settings: https://support.google.com/accessibility/android/answer/6006554

**Comment by Wiredframe** [comment]
Can’t believe I didn’t update before! Thanks, now it’s working as expected.
