### ISSUE TITLE
Leanback flag for direct lauch on Android TV - Could you please add?

### ISSUE THREAD

**Issue by gnarf49** [mediathekview/zapp#223]
Zapp runs perfectly fine on Android TV (in this case a Sony Bravia Android 9) but it can't be started directly or added as favorite to the telly's home screen because of a missing flag required to mark it compatible with Android TV. 
To launch, one must go via Settings/Apps/SystemApps and scroll down some pages of apps.

If possible, could you please mark Zapp as TV compatible so it can be launched from the Android TV home screen?

**Comment by gnarf49** [comment]
Just found in the Pull Request section this already wip. Hope it will be ready soon, trying Chainfire's TV launcher or similar meanwhile.

**Comment by cemrich** [comment]
Thank your very much for your feedback. I am afraid, this will take a while due to pandemic craziness :(
