### ISSUE TITLE
Download stops, when app is in background

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#224]
Downloads stop as soon as the app is no longer in the foreground.

Android 10
Samsung Galaxy XCover 4s
ZAPP 3.6.1

**Comment by cemrich** [comment]
Thank you for reporting! I'll try to reproduce this on different devices.

**Comment by cemrich** [comment]
I cannot reproduce this on my devices (Galaxy S7, Android 7 & Poco F1, Android 11). Is anyone else able to reproduce this issue?

@WebworkrNet Is it possible your device has any power saving option enabled that might interfere with the downloads?

**Comment by WebworkrNet** [comment]
The following screenshot shows the current settings. I will turn off the optimization and test again.

**Comment by WebworkrNet** [comment]
[cid:eu.faircode.email.957]

**Comment by cemrich** [comment]
@WebworkrNet Thanks for your feedback. As background activity is allowed, the download should work just fine... It is the same setting as on my device.

**Comment by WebworkrNet** [comment]
Ignoring the battery optimization does not bring any improvement.

**Comment by WebworkrNet** [comment]
[cid:eu.faircode.email.982]

 [cid:eu.faircode.email.983]

**Comment by cemrich** [comment]
@WebworkrNet Thanks for checking that! I'll try to reproduce this issue on an emulator so I am able to fix it.

If anyone else experiences issues with stopped downloads, please leave a comment!

**Comment by WebworkrNet** [comment]
Only briefly displayed PUSH error message: "Connection timed out".

I'm trying to add screenshots that have been made here. Unfortunately I have problems uploading files at the moment. Images are not displayed, only the file path.

**Comment by WebworkrNet** [comment]
Sorry, but I can't confirm, that the problem is fixed.

**Device**: Samsung Galaxy XCover 4s (SM-G398FN)
**Operating System**: Android 11
**Zapp**: 5.0.2

**Comment by cemrich** [comment]
Nice, I can't reproduce this with my devices :(
Judging from other user feedback, this issue is fixed for most users. But "this issue" may in fact be multiple issues -  I cannot tell right now.

**Comment by WebworkrNet** [comment]
I will keep an eye on it and report back.

**Comment by WebworkrNet** [comment]
Sorry, but I can't confirm, that the problem is fixed.

**Device**: Samsung Galaxy XCover 4s (SM-G398FN)
**Operating System**: Android 11
**Zapp**: 7.0.3

**Comment by cemrich** [comment]
> An exception is when a live stream is playing in the background at the same time and the screen is then locked by the system (https://github.com/mediathekview/zapp/issues/241).
Then the error does not occur.

**Comment by cemrich** [comment]
Sound like the app gets killed. I suspect the download service.

**Comment by WebworkrNet** [comment]
> > An exception is when a live stream is playing in the background at the same time and the screen is then locked by the system (https://github.com/mediathekview/zapp/issues/241).
> Then the error does not occur.

This is correct.

**Comment by cemrich** [comment]
Can you please confirm that this issue is fixed with v8.0.0?

**Comment by WebworkrNet** [comment]
Issue is fixed.
Great :-)

**Comment by cemrich** [comment]
Yesssss! Thanks for testing!
