### ISSUE TITLE
Show Zapp on Android TV home screen (Leanback launcher)

### ISSUE THREAD

**Issue by uragan1208** [mediathekview/zapp#225]
Hallo,
eine Frage in die Runde.
Unter Android 10 (Android TV) wird die App als Systemapp eingestuft und lässt sich somit nicht auf dem Homescreen anzeigen. Gibt es eine Möglichkeit dies zu ändern? Evtl. kann es beim Build vom neuen Release berücksichtigt werden. Danke vorab für die Hilfe.

Gruß
uragan1208

**Comment by cemrich** [comment]
(Spätes) Danke für das Feedback!

Es gibt eine Möglichkeit, die Umsetzung wird allerdings noch etwas dauern.

Pull-Request als Referenz: #191

**Comment by upost** [comment]
@uragan1208 Mein Fork kann das. Ist bloß (immer noch) nicht hier in den Master gewandert, da @cemrich dafür keine Zeit findet.
Leider ist mein Fork inzwischen 250 commits behind und ich hab keine Lust, die ganzen Änderungen bei mir rein zu mergen.
Also ziemlich veraltet, läuft aber definitiv, na ja, sagen wir 95% stabil auf einem Android 10 TV. Kannste also auschecken, bauen und sideloaden und mal testen.
https://github.com/upost/zapp/

**Comment by cemrich** [comment]
Please check out the new Android TV version [7.0.0 Beta](https://github.com/mediathekview/zapp/releases/tag/7.0.0-beta)!
