### ISSUE TITLE
HR-Stream geht seit einiger Zeit gar nicht.

### ISSUE THREAD

**Issue by justf0rfun** [mediathekview/zapp#226]
Bei mir geht der HR-Srteam seit einiger Zeit gar nicht. 

Es kommt sofort die Meldung, dass das Video nicht geladen werden konnte, womöglich weil man keine Internet-Verbindung habe oder das Video im eigenen Land nicht verfügbar sei.

Hat sich vielleicht die URL des Streams geändert? 

Android 6.0

Gibt es möglicherweise einen Zusammenhang mit folgendem Issue?
https://github.com/mediathekview/zapp/issues/220

**Comment by cemrich** [comment]
Die Url hat sich geändert und ist jetzt wieder aktuell. Einfach Zapp einmal komplett beenden, neu öffnen und alles sollte wieder funktionieren :)
