### ISSUE TITLE
BR Süd doesn't show the correct live stream

### ISSUE THREAD

**Issue by buergi** [mediathekview/zapp#227]
The configured [live stream](http://livestreams.br.de/i/bfssued_germany@119890/master.m3u8) does always stream the same content, when it is selected. It is not the correct live stream. BR Nord does work correctly. A working BR Süd stream is available under [this URL](https://mcdn.br.de/bfs_sued/de/master.m3u8).

**Comment by cemrich** [comment]
Thank you for your feedback! The url has been updated - you have to close and restart Zapp to continue watching BR Süd.
