### ISSUE TITLE
Streams are sometimes stopping

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#229]
It reminds me on the timeout issue that we once had with regular downloads.
What would be the best way to create debugging data for you?

**Comment by cemrich** [comment]
Is this still the case?

**Comment by alexanderadam** [comment]
To be honest: I don't know.
Nowadays I'm downloading everything with Zapp and watch it offline.

But since nobody else commented on this I will close it (I can reopen it anyway in case I find out that it still occurs).

**PS:** Thank you for Zapp and your patience with my issues 😆

**Comment by cemrich** [comment]
Thank you!
