### ISSUE TITLE
Portrait mode: Image content is cut off on the right and left

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#231]
In portrait mode, the stream is not scaled to the screen format. Image content is cut off on the right and left.

Samsung Galaxy XCover 4S
Android 10
Zapp 3.6.1

**Comment by WebworkrNet** [comment]
Unexpectedly, I was able to optimize the screen display after tapping the center of the screen in the running stream. The display is therefore now sustainably okay.

However, it is unclear why the portrait mode does not load correctly by default.

**Comment by cemrich** [comment]
There is a "pinch to zoom" gesture for devices with a non 16:9 aspect ratio. It should not crop anything by default. Maybe you ran into this feature by accident?

**Comment by WebworkrNet** [comment]
Yes, that can be.
