### ISSUE TITLE
Media library: Display of the remaining download time for long program titles not visible in the notifications

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#235]
Media library: Display of the remaining download time for long program titles not visible in the notifications

Starting position:
In the notifications, the remaining download time is shown behind the program title.

Problem:
If the title is very long, it will be introductory at the end with 3 dots at the end
cut off. The indication of the remaining download time also falls victim to the cut.

Suggested solution:
Position the indication of the remaining download time in a new line.

**Comment by WebworkrNet** [comment]
Samsung Galaxy XCover 4s
Android 10
Zapp 3.6.1

**Comment by WebworkrNet** [comment]
![20210530_092658](https://user-images.githubusercontent.com/43509007/120096046-97d3eb80-c129-11eb-8371-4dfb09ed400c.jpg)

**Comment by cemrich** [comment]
Thank you very much for this report!

I can confirm this behavior for Android 11, Poco F1.

**Comment by cemrich** [comment]
Remaining time display is not supported in the upcoming version, so I'll close this for now.

**Comment by WebworkrNet** [comment]
For now? That is, the problem will be taken up again at a later date?
