### ISSUE TITLE
Live stream [DW Deutsch] and [DW Deutsch+] do not work

### ISSUE THREAD

**Issue by justf0rfun** [mediathekview/zapp#237]
## Which channel does not work correctly?
DW Deutsch and DW Deutsch+

## What is the problem?
- [x] does not load at all
- [ ] shows always the same looping content
- [ ] performance problem (stuttering or other)
- [ ] other problem (add description)

I assume that only the stream URLs are out of date. The streams can be found on the DW website:

https://m.dw.com/de/media-center/live-tv/s-100817

Unfortunately I don't have access to a desktop system atm to find out the actual streaming URLs.

**Comment by cemrich** [comment]
urls:
- dw: https://dwamdstream106.akamaized.net/hls/live/2017965/dwstream106/index.m3u8
- dw+: https://dwamdstream105.akamaized.net/hls/live/2015531/dwstream105/index.m3u8

**Comment by cemrich** [comment]
Done and will be deployed by tomorrow.

**Comment by cemrich** [comment]
Fixed! You have to restart Zapp to get the correct stream. Please report any further problems,
