### ISSUE TITLE
Zapp does not show the ARD ONE livestream

### ISSUE THREAD

**Issue by rojoweko** [mediathekview/zapp#238]
Zapp does not show a livestream, but seams to start always at the same point in the middle of some videofeed (from the mediathek?) when the ARD ONE livestream is being selected. I was able to reproduce this on several devices (via a mobile connection).

**Comment by cemrich** [comment]
new url: https://mcdn.one.ard.de/ardone/hls/master.m3u8

**Comment by cemrich** [comment]
Done and will be deployed by tomorrow.

**Comment by cemrich** [comment]
Also RBB Berlin and RBB Brandenburg have been fixed.

**Comment by cemrich** [comment]
Fixed! You have to restart Zapp to get the correct stream. Please report any further problems,

**Comment by rojoweko** [comment]
Great! Thanks a lot! :-)
