### ISSUE TITLE
Background playback: screen lock not prevented

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#241]
Initial situation: Background playback

Provided there is no interaction with the device, the screen lock is activated and the audio signal continues to be played.

Is this behavior normal or is it a bug? I would expect playback to prevent the screen lock regardless of the playback mode.

**Comment by cemrich** [comment]
Thank you very much for your feedback!

This is exactly the behaviour I would expect from the Android system:
- Picture-In-Picture: screen lock does not activate on inactivity
- Background playback: screen lock does activate on inactivity; sound continues to play
- "regular" in app playback: screen lock does not activate on inactivity

Please let me know if you have further questions!

**Comment by WebworkrNet** [comment]
Thank you
