### ISSUE TITLE
Large downloads stop even when not in background

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#249]
> This bug seems to occur especially when downloading videos in highest resolution it seems that this is the situation in which most abortions occur.
> 
> Most time it's like described below:
Most times when starting to download a high resolution video, the download doesn't complete but aborts after some time, e.g. when about a third is completed. When restarting the download (by using the workaround), then it gets a little further, let's say about ⅜ this time, for example. Next time, it gets a little further again, and so on and so on, until the download is finally finished.
It seems to me that everytime the download aborts, the part that's done so far is cached somewhere and by everya new try a little more can be downloaded before it fails again.
Maybe the download function is just a little too 'impatient'?

May be related to #233

**Comment by WebworkrNet** [comment]
How do you define `large` downloads?

**Comment by cemrich** [comment]
I tested with movies and shows (>90min) in high quality

**Comment by WebworkrNet** [comment]
Feedback:
So far I have been able to successfully test videos with a length of approx. 45 minutes at medium quality. (High quality was not available for selected titles).
