### ISSUE TITLE
Fix transifex resources

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#253]
It is missing the "master" branch, which is now "main".

**Comment by eUgEntOptIc44** [comment]
Hi @cemrich @comradekingu did the (possible) weblate integration happen. If not I'd be very grateful if you had the time to long into this anytime soon.

**Comment by comradekingu** [comment]
I am on it. Asked bubu. Will otherwise go with Hosted Weblate.

**Comment by Bubu** [comment]
The instance at https://weblate.bubu1.eu is open for signup for new projects. Whoever creates a project is automatically an admin for it and should be able to add other project admins. Let me know if something doesn't work.

**Comment by comradekingu** [comment]
The problem was on my side. My brain works now.
https://weblate.bubu1.eu/projects/zapp/

Targeting "develop" for PRs.

**Comment by comradekingu** [comment]
@eUgEntOptIc44 
So the -en one is selected as en_UK, but those are German strings in there.
Can't change the base language, so I am going to have to set it up again.
Before I get into another problem, why are there two resources that are seemingly English?

**Comment by eUgEntOptIc44** [comment]
@comradekingu first of all thank you for quick reaction to my message. 👍 

Tbh I didn't noticed the [`strings.xml`](https://github.com/mediathekview/zapp/blob/15e85b6055ce231db3e37854cc027fda5783805a/app/src/main/res/values/strings.xml) in `values/` being German not English. Sorry my fault ... I might have better had a second read through the source code. 

To my personal understanding this seems to be only show blocker right now. Am I right? @comradekingu would love to hear your feedback on this as your far more experienced with weblate than myself.

I tried to apply the feedback by @comradekingu in PR #323. Would be great if @cemrich could or anyone else reading this give me some feedback on this. Please be aware that my knowledge of kotlin and development for android is quite limited.

While do so I stumbled across [`donottranslate.xml`](https://github.com/mediathekview/zapp/blob/be13231472cccd0c36f85f9b59b42605d27e9868/app/src/main/res/values/donottranslate.xml) and tried to match this against strings.xml but didn't get anywhere.

**Comment by comradekingu** [comment]
@eUgEntOptIc44 
Looks good. I wasn't actually in "reviewers" for that PR. Sorry to have missed whatever other messages I may have overlooked.
:)

**Comment by cemrich** [comment]
Thank you very, very much for your effords!

I will not be able to look into this for the next few days, but I can clarify a few things:

- [`donottranslate.xml`](https://github.com/mediathekview/zapp/blob/be13231472cccd0c36f85f9b59b42605d27e9868/app/src/main/res/values/donottranslate.xml) are configuration strings that should not be translated.
- The base language should be German - this does make sense, since most of the apps content is German anyway. The second language should be American English.

I'll let you know as soon as I have some spare time.

**Comment by eUgEntOptIc44** [comment]
Well first of all thanks for looking into this. I really love the app and I'm happy to help.

> donottranslate.xml are configuration strings that should not be translated.

Thanks for clarification. 👍 

> The base language should be German - this does make sense, since most of the apps content is German anyway. The second language should be American English.

To me personally this looks like a misunderstanding. I set English as the default so that I would work as a **fallback**. Take the following use case: an user locating within the boundaries of the geo-blocking (so likely Germany or France) using a device with a French, Italian, Turkish, Ukrainian ... or other not German or English locale is using the app. They would still see the English locale instead of the German.

Especially for learning German and receiving trustworthy informations by watching German TV channels the app proves very useful. To cut it short I'd ease the bar.

**Comment by comradekingu** [comment]
I set it up on https://hosted.weblate.org/projects/zapp/#information instead, since bubu WL is moving over to the Codeberg WL.

@eUgEntOptIc44 
I didn't quite understand that, but the user decides on the language, and after Android  9(?) multiple languages can be selected in Android, for fallback.
In Android 13, there is per app management of languages from Android.

**Comment by cemrich** [comment]
@eUgEntOptIc44 I commented your PR

Multiple locales can be selected since Android 7.0 (https://developer.android.com/guide/topics/resources/multilingual-support). 

Per app language support is available with Android 13 (https://developer.android.com/guide/topics/resources/app-languages). But I have to enable that explicitly. I've created a new issue for that: https://github.com/mediathekview/zapp/issues/327

**Comment by comradekingu** [comment]
@eUgEntOptIc44 Seems to work now.
Add https://docs.weblate.org/en/latest/admin/continuous.html#github-setup and possibly
https://github.com/weblate to the org, and
https://github.com/marketplace/actions/weblate-locale-linter

**Comment by comradekingu** [comment]
Just needs #329 now.

**Comment by cemrich** [comment]
@comradekingu If you could add me (@ccoenen) as admin, that would be nice.

**Comment by cemrich** [comment]
Okay, I am still unsure about the default locale.

If I were a spanish or turkish user and my preferred languages are not supported in Zapp - what fallback language would I expect?
1. English, because the likelihood of me understanding even little bits and pieces is higher
2. German, because all other content (video language, show information, etc.) is served in German
