### ISSUE TITLE
Failed Downloads cannot be removed from download list

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#257]
I welcomed the introduction of the "`Downloads`" tab. I wanted it suggested already and now it's there. :-)

However, I have not yet found a way to remove list entries.

**Comment by WebworkrNet** [comment]
Missed downloads (e.g. #233) cannot be cancelled, but only restarted.

It is possible that a new download (attempt) at a later time is no longer desired or that the source is no longer available because the content has been removed from the broadcaster's media library.

In this case, so-called "corpses" occur.

**Comment by cemrich** [comment]
Yes, this is a problem edge case at the moment. I'll transfor this issue in a bug ticket to reflect that.

**Comment by cemrich** [comment]
In the upcoming version 6.1.0 there will be the possibillity to remove any download on long press on the list item.

**Comment by WebworkrNet** [comment]
Thank you :-)
