### ISSUE TITLE
Screen lock takes effect when a download is in progress in the foreground.

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#261]
**Device**: Samsung Galaxy XCover 4s (SM-G398FN)
**Operating System**: Android 11
**Zapp**: 5.02

While the app is in the foreground and busy with a download, the screen lock takes effect.

Is this the way it should be, or is a corresponding function not currently implemented, or is it a bug?

**Comment by cemrich** [comment]
This is expected behavior. There is no reason to keep the screen on in this case.

**Comment by WebworkrNet** [comment]
I assume that the download will then continue despite the screen lock, leaving aside #224.

**Comment by cemrich** [comment]
> I assume that the download will then continue despite the screen lock, leaving aside 

Yes, downloads should continue to run in background.
