### ISSUE TITLE
"Play" button: Distinction between stream and local file?

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#262]
Does it make a difference whether the video file is available locally after downloading or is the video streamed from the respective server in any case when the "Play" button is pressed??

![Screenshot_20211107-111640_Zapp](https://user-images.githubusercontent.com/43509007/140641544-c48c88d5-77e2-4afa-a385-1fc977447648.jpg)

**Comment by cemrich** [comment]
Whenever available, the local file will be used for playback.

**Comment by WebworkrNet** [comment]
I was irritated because when I played it in the Zapp player, the video file ("Psst!", screenshot), which is about 120 MB in size, was not completely loaded immediately at the beginning, even though it is available locally.

**Comment by cemrich** [comment]
I just confirmed that the local file is loaded. ExoPlayer seems to load the video file in chunks from disk.

**Comment by WebworkrNet** [comment]
Thanks for clearify.

**Comment by WebworkrNet** [comment]
Would you like to add this question to the FAQ, @cemrich?
