### ISSUE TITLE
Suche in Mediathek auf Fire TV seit Version 6.0.0 nicht mehr möglich

### ISSUE THREAD

**Issue by lxne** [mediathekview/zapp#270]
Zapp 6.0.0 (53)
Fire TV Stick

Seit Version 6.0.0 ist es leider nicht mehr möglich mit der Fire TV Fernbedienung das Suchfeld im Mediathek-Tab zu aktivieren. Somit ist die Suchfunktion nicht nutzbar. Es wäre super, wenn das wieder korrigiert werden könnte.

Und für's Protokoll:
Zapp ist einfach suuuuuuuper!

**Comment by cemrich** [comment]
Vielen Dank für das Feedback!

Es wird in Zukunft eine spezielle Version für Android-TV geben. Bis dahin muss ich den TV-Support leider etwas hinten an stellen.

**Comment by lxne** [comment]
Danke für die Antwort.
Am Fire TV funktioniert sonst alles. Es kann nur leider das Suchfeld nicht angesprungen werden.

**Comment by cemrich** [comment]
Please check out the new Android TV version [7.0.0 Beta](https://github.com/mediathekview/zapp/releases/tag/7.0.0-beta)!
