### ISSUE TITLE
Enlarge timeline-button

### ISSUE THREAD

**Issue by kojid0** [mediathekview/zapp#272]
On a tablet, the timeline button on the bottom right-hand side is too small, resulting in bad UX
![grafik](https://user-images.githubusercontent.com/24477557/145676503-e68ed31a-1788-4dac-a86c-2a0cb4b5c692.png)

**Comment by cemrich** [comment]
Yes, it seems quite small. I'll give this low priority, as you can always touch the timeline without using the button.

**Comment by kojid0** [comment]
> Yes, it seems quite small. I'll give this low priority, as you can always touch the timeline without using the button.

Yes, but IMO the timeline is too small as well. You either hit too close to the content (timeline disappears) or hit too close to CC/Settings Button.

**Comment by cemrich** [comment]
Please check out the new version [7.0.0 Beta](https://github.com/mediathekview/zapp/releases/tag/7.0.0-beta) where the button is a bit larger. More tablet optimizations will follow.

**Comment by kojid0** [comment]
It's way better now, thanks!
