### ISSUE TITLE
Background-Playback stops after one minute

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#273]
- even with screen on
- tested on Android 11

**Comment by Aufschlauer** [comment]
Hi,

I notice that when I start "Im Hintergrund abspielen" playing stops after 5 minutes. Verified on 2 devices: Android 7 and Android 10.

So when my issue is targeting #273 I would give it a :+1: :-) .

**Comment by cemrich** [comment]
@Aufschlauer Yes, this should be the same issue. A bugfix release is due, fut free time rare :( I'll comment this issue as soon as a bugfix version has been released.

**Comment by cemrich** [comment]
Version 6.0.2 has just been released and should hit F-Droid in a few days. 

@Aufschlauer Feel free to reopen this issue, if the problem is not fixed in your case.

**Comment by reiner-text** [comment]
Works now, also with Android 12 with One UI 4.0 on a Galaxy A72. Thank you! 👍🏻
