### ISSUE TITLE
unusable on firetv 

### ISSUE THREAD

**Issue by vladtepesch** [mediathekview/zapp#274]
### explanations
it would be great to have an app on firetv that gets access to the mediathek contents of the public broadcasting services because their content is spread over different apps with strange searchs.
Sadly neither the mediathekview app nor this app is currently usable with the remote on firetv.

### current problems
- No logo on fire tv app menu (since no captions is displayed its always guesswork which iconless app (this may be an fault of the fireos on how to load which icon - see this discussion on similar issue https://github.com/TeamNewPipe/NewPipe/issues/5256 and the there inked https://github.com/TeamNewPipe/NewPipe/pull/6166) is which one)
- difficult to navigate to mediathek section
- impossible to navigate to search box
- on stream playback fast forward and fast reward with remote keys is very slow if one wants to skip larger parts

### device info:
Device: Amazon FireTV Stick Model: AFTSSS
[ro.build.mktg.fireos]: [Fire OS 7.2.4.2]
[ro.build.version.base_os]: [PPR1.180610.009]
[ro.build.version.fireos]: [7.0]

**Comment by cemrich** [comment]
Thank you very much for this feedback! 

Android TV is on my TODO list (see [Android TV Project](https://github.com/mediathekview/zapp/projects/12)) and partly implemented in tv friendly ui. However, free time is rare right now and a polished release will have to wait a bit longer.

Also, there could be some problems with FireTV regarding ExoPlayer: 

> FireOS (version 4 and earlier) - Whilst we endeavour to support FireOS devices, FireOS is a fork of Android and as a result we are unable to guarantee support. Device specific issues encountered on FireOS are normally caused by incompatibilities in the support that FireOS provides for running Android applications. Such issues should be reported to Amazon in the first instance. We are aware of issues affecting FireOS version 4 and earlier. We believe FireOS version 5 resolved these issues.

My first priority will be plain Android TV. But firetv will most likely work too.

**Comment by cemrich** [comment]
Related to #270

**Comment by vladtepesch** [comment]
![grafik](https://user-images.githubusercontent.com/1601159/170702340-bd332921-f43a-4060-87f2-4aca6847fcc0.png)

installed it but only get a crash on stating it - also there is no app icon displayed in the app selection

FireOS 7.2.7.9
FireTV Stick 3rd gen (AFTSSS
