### ISSUE TITLE
Number of search results

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#277]
Nice to have: Show the number of search hits when the entire dataset is restricted by search terms and/or other filter criteria.

Compare Mediathekviewweb.

**Comment by cemrich** [comment]
Yes, this is a nice suggestion!

**Comment by cemrich** [comment]
Filmlist date and number of results will be displayed in the upcoming version 6.1.0

**Comment by WebworkrNet** [comment]
1. The display returns a zero value.
2. I also find the placement unfortunate. The display is only visible when the filter options are called up.

![Screenshot_20220714-190913_Zapp](https://user-images.githubusercontent.com/43509007/179118567-933368f2-f96d-4db0-90cf-013a374bf695.jpg)

**Comment by WebworkrNet** [comment]
Compare #278.
