### ISSUE TITLE
Display: Timestamp last update film list

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#278]
Compare footer Mediathekviewweb.

Example: 
`Film list last updated on 08.03.2022 at 23:18.`

**Comment by cemrich** [comment]
Filmlist date and number of results will be displayed in the upcoming version 6.1.0

**Comment by WebworkrNet** [comment]
1. The display returns a zero value.
2. I also find the placement unfortunate. The display is only visible when the filter options are called up.

![Screenshot_20220714-190913_Zapp](https://user-images.githubusercontent.com/43509007/179118567-933368f2-f96d-4db0-90cf-013a374bf695.jpg)
