### ISSUE TITLE
Merge duplicates (same channel)

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#279]
Duplicates appear in the list of available programmes. Unlike #228, however, I am referring to identical programmes on the same channel.

Example:
MaiThink X - Die Show - Sternstunden der Neolution - Teil 1
`https://rodlzdf-a.akamaihd.net/none/zdf/21/10/211004_neolution_mai/2/211004_neolution_mai_3360k_p36v15.mp4`

- Mediathekviewweb 1x listed.
- Zapp 2x listed.

**Comment by WebworkrNet** [comment]
Another example:
MaiThink X - Die Show	
Kritisches Denken - mit Lutz van der Horst & Fabian Köster
`https://rodlzdf-a.akamaihd.net/none/zdf/21/10/211022_kritisches_denken4_mai/1/211022_kritisches_denken4_mai_3360k_p36v15.mp4`

- Mediathekviewweb 1x listed.
- Zapp 2x listed.

**Comment by strelitzer** [comment]
I can only find/see both programs once in Zapp.

**Comment by cemrich** [comment]
I can't reproduce this issue either.

**Comment by cemrich** [comment]
I'll close this for now. Feel free to open a new issue if this ever happens again.

**Comment by cemrich** [comment]
This is an old one, but I could reproduce this issue and fixed it. There was an issue with the paging keys, so some entries (number 60 to 90 in the list) were loaded two times.
