### ISSUE TITLE
Channel "Tagesschau24" is in loop

### ISSUE THREAD

**Issue by Ste-denko** [mediathekview/zapp#280]
## Which channel does not work correctly?
Tagesschau24

## What is the problem?
- [ ] does not load at all
- [x] shows always the same looping content
- [ ] performance problem (stuttering or other)
- [ ] other problem (add description)

The stream is looping since yesterday morning (11.03.).
This occurs on two different devices since then.
Deleting memory and cache or reinstalling did not help.
Thank you very much in advance for your help!

By the way ... Zapp is just a very cool App, thanks a lot!

**Comment by Ste-denko** [comment]
The loop of this channel has stopped and the stream is working again as expected.

**Comment by cemrich** [comment]
Thank you very much for reporting! I fixed the stream url and forgot to close this issue :)
