### ISSUE TITLE
Tagesschau not available

### ISSUE THREAD

**Issue by shruuub** [mediathekview/zapp#281]
Hello. So I've noticed that tagesschau(20:00Uhr) isnt available. The 15:00 Uhr version for example is, as well as tagesschau24? Is there any reason for this?

**Comment by cemrich** [comment]
Thank you very much for your report!

Do you mean tagesschau as show in the "Mediathek" tab? If so, can you please verify the show is showing up on [mediathekviewweb.de](https://mediathekviewweb.de) but not on Zapp?

**Comment by shruuub** [comment]
> Thank you very much for your report!
> 
> Do you mean tagesschau as show in the "Mediathek" tab? If so, can you please verify the show is showing up on [mediathekviewweb.de](https://mediathekviewweb.de) but not on Zapp?

Ah, sorry, I wasn't aware how zapp gets it's results. It isnt showing on mediathekviewweb.de either.

**Comment by cemrich** [comment]
No problem! 

If it's not showing up in mediathekviewweb, there is nothing I can do in Zapp. You may want to report the missing show in the forums: https://forum.mediathekview.de/category/7/fehlende-sendungen
