### ISSUE TITLE
Suggestion: Hide top bar when playing after some time

### ISSUE THREAD

**Issue by sbellon** [mediathekview/zapp#285]
Today I installed Zapp 6.1.0 on my Fire TV. While it clearly is not optimized for TV use, it works pretty well. The only thing that really is preventing a good TV full screen experience is the fact that the top bar (with back, title, share, info, settings) is staying on the screen all the time. I have not found any way to hide it. If it would hide after 10 or 15 seconds (and reappar on any input), it would be perfectly suited for Fire TV already as it is.

Perhaps this small change could be given some consideration until the Android TV project is ready?

**Comment by strelitzer** [comment]
It is a new bug in v6.1.0. In prior versions the top bar was hidden after some seconds.

On my Android device I have to tap on the screen to hide the bar.

**Comment by sbellon** [comment]
Yes, on my Android phone I also can tap on the screen, this is not so easy on the Fire TV. ;)

So, if you say that worked with 6.0.0, I'll try to use that on the Fire TV.

**Comment by sbellon** [comment]
Yes, in 6.0.2 it works. So this is a "bug" rather than a "suggestion".

But for the time being, I'll just use 6.0.2 on the Fire TV. :-)

**Comment by cemrich** [comment]
Thank you all very much for your feedback!

At the moment Zapp is barely usable on Android TVs so I do not test (ui) changes on these devices. I am working on a specialized Android TV ui based on leanback and making good progress. This version will have less features (eg. no downloads or advanced filters) in favor of a lean an optimized user interface.

Please be patient a little bit longer :) Also, at the moment there should be no harm in sticking to an older version.

**Comment by sbellon** [comment]
I hope this comment does not reopen the issue ... if so, feel free to close again.

I just want to let you know that I would be happy to test this specific TV version of the app when you are at a point where you'd like to have some testers.

**Comment by strelitzer** [comment]
Das Verhalten, dass die obere Leiste nach dem Aufrufen eines Senders nicht nach ein paar Sekunden automatisch verschwindet, ist ein Bug in Version 6.1.0, der vorher nicht da war.
Soll ich dafür ein neues Problem erstellen?

**Comment by strelitzer** [comment]
I am also going back to v6.0.2 on my android. The top bar that no longer disappears automatically in v6.1.0 is just annoying. ``wontfix`` also means that this should remain so.

**Comment by TobiasHB** [comment]
Just a hint: Pausing and unpausing the stream makes the bar go away after a few seconds on my Fire TV with Zapp 6.1.0.

**Comment by strelitzer** [comment]
> It is a new bug in v6.1.0. In prior versions the top bar was hidden after some seconds.

The bug is fixed with v7.0.0-beta.

**Comment by sbellon** [comment]
What crash message are you looking for?
