### ISSUE TITLE
Klick on download finished notification does nothing when app is in background

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#288]
This is due to a new Android restriction in Android 12:

`NotificationService: Indirect notification activity start (trampoline) from de.christinecoenen.code.zapp blocked`

Documentation: https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines

**Comment by cemrich** [comment]
Yes, the notification is there. But on Android 12 nothing happens when you click it. I'll adjust the title of this issue :)

**Comment by strelitzer** [comment]
Sorry I deleted my comment **after** reading the linked article. I have to read first and answer then.

**Comment by cemrich** [comment]
A fix is available with version 7.0.1.
