### ISSUE TITLE
feature request: allow adjusting quality and playback speed in mediathek

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [mediathekview/zapp#297]
As of now, it is not possible to adjust the quality of the stream in the mediathek playback. For the playback speed, only a few predefined options are available.

I would like to propose to a) allow selection of stream quality in case the mediathek server features different qualities (e.g. ZDF does) and b) add an option for custom speed *or* a few more predefined options.

**Comment by cemrich** [comment]
Thank you very much for your feedback!

I try to use [exoplayers ](https://exoplayer.dev/) (very nice) default interface to make maintenance for Zapp as painless and efficient as possible and focus on other features and bugfixes. More playback speeds and quality selection would add so much code to the app - I don't think it is woth it.

However, you can adjust the default quality for metered networks in the settings.
