### ISSUE TITLE
FireTV Stick 4K - v7.0.3 - Place the "Live, Mediathek, Downloads and search bar" to the top again (please)

### ISSUE THREAD

**Issue by rorar** [mediathekview/zapp#306]
Hi,

I had previously the v7.0.2 installed here from GitHub.
In this release I was able to navigate from a top bar nav menu and that improved the app navigation with the FireTV remote drastically.
In v7.0.3 it seems to be reverted to the old state.
I'd ask you to either add the top bar nav menu or a toogle inside the settings to switch between top and bottom. 

Thanks :)

**Comment by cemrich** [comment]
There should be no difference whatsoever in the UI between 7.0.2 and 7.0.3. Can you please verify, that 7.0.2 was the "working" TV version?
Have you started Zapp from withing F-Droid or from the main menu? Starting it from the main menu (launcher) should open the Android TV version of Zapp with the optimized top navigation bar.

**Comment by cemrich** [comment]
I will close this issue because of missing feedback. Please feel free to open a new one if needed.
