### ISSUE TITLE
Problem distniguishing metered/unmetered networks

### ISSUE THREAD

**Issue by xandro0777** [mediathekview/zapp#307]
Hi, I am using the latest release from F-Droid. On one of my WLANs zapp for some reason thinks it is a metered network even though I would like to treat it as unmetered.

Can't enable use on all networks because I don't want to use up the LTE Volume.

Any idea for a workaround? Could there be an option to treat all WLANs as unmetered?

TIA

**Comment by xandro0777** [comment]
BTW googled around and found how to set a WIFI as metered but can't find this option on my Android 12 system.

**Comment by cemrich** [comment]
Yes, this is a system setting and differs on every operating system. On my system I am able to edit the wifi connection and set it to (un)metered - hidden behind a "more options" dropdown.
