### ISSUE TITLE
Show meaningful duration

### ISSUE THREAD

**Issue by MatsG23** [mediathekview/zapp#308]
When watching a stream live, the duration skips back a bit after reaching the full length of the duration bar.

Can a real duration for the playing show be displayed? If this is not possible, I propose to just show "live" when you are watching live (like it is done on YT live streams).

**Comment by cemrich** [comment]
Thank you very much for your feedback!

However, I like the duration display, because the live window for skipping forward/backward is clearly visible to the user. In addition, it is more work to replace it than to leave it as is.

**Comment by WebworkrNet** [comment]
I understood it to mean that the progress display as well as the time display is not correct in live mode.

![Screenshot_2022-12-26_14-53-54](https://user-images.githubusercontent.com/43509007/209557315-42c07c17-f390-4781-8070-087f1a60da2f.png)
![Screenshot_20221226_145131_Zapp](https://user-images.githubusercontent.com/43509007/209557355-1673d2bd-2a80-430d-9788-f61f5bd5f0e2.jpg)
