### ISSUE TITLE
Resume interrupted downloads

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#309]
Failed downloads currently have to be restarted from the beginning. This not only wastes time, but also consumes data. In times of climate protection, it would be advantageous to turn off this unnecessary data traffic. Hence my suggestion to add the appropriate functionality of a download manager.

**Comment by cemrich** [comment]
This has implications like:
- What happens to half downloaded files that are never re-downloaded? We do not want to clutter the download directory with random bytes we will not use ever again.
- Does the download server support resuming downloads? How do we find out?
- Does the no longer maintained fetch download library support resuming downloads?

**Comment by cemrich** [comment]
Resuming failed downloads will happen automatically (for a limited number of retries) in the next release.

**Comment by cemrich** [comment]
This issue is fixed with version 8.0.0
