### ISSUE TITLE
Download aborts on screen lock

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#311]
**Device**: Samsung Galaxy XCover 4s
**OS**: Android 11
**App**: 7.03

**Comment by WebworkrNet** [comment]
Related to #261.

**Comment by WebworkrNet** [comment]
Related to #224.

**Comment by WebworkrNet** [comment]
An exception is when a live stream is playing in the background at the same time and the screen is then locked by the system (#241). 
Then the error does not occur.

**Comment by cemrich** [comment]
Duplicate of #224
