### ISSUE TITLE
Playback: Horizontal settings

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#312]
Among other things, the volume can be adjusted by swiping horizontally across the screen while playback is in progress. 

On the smartphone, I often have the problem that I accidentally press these controls when I call up the status bar or quick settings of the device.

Can the display of the sliders be optimised? Thank you

**Comment by cemrich** [comment]
The behaviour changed in version 7.0.4. Is this better now?

**Comment by WebworkrNet** [comment]
Fine :-)
Thanks
