### ISSUE TITLE
Timestamp of last updated filmlist and number of search results may be null

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#314]
See #278 and #277

**Comment by cemrich** [comment]
I cannot reproduce this anymore. Maybe the backend changed?

**Comment by cemrich** [comment]
Funny thing - this does only happen in release builds. But it doesn't seem to be a minifier/proguard issue.

**Comment by cemrich** [comment]
Some optimization tool stripped away my model in release builds. This should be resolved in the next release.

**Comment by WebworkrNet** [comment]
Thank you, seems to be fixed now. :-)

**Comment by cemrich** [comment]
This issue is fixed with version 8.0.0
