### ISSUE TITLE
Improve or revice audio and brightness swipe controls.

### ISSUE THREAD

**Issue by justf0rfun** [mediathekview/zapp#317]
Actually the swipe gesture is really nice. I guess you developers had put some effort in it, which I appreciate. On the other side it can be tricky to swipe to the extremes meaning to the edges of the screen. That is probably even more difficult for people with bigger fingers. It has been a bit tricky with my old device and it is even more tricky with my new device, the FP4. This may a bit on if and what kind of covering case is used to protect the device.

Hence it may be considered to change the swipe gesture. I guess the approach with the least effort would be to narrow down the total height of the swipe area, so that users don't have to swipe to the display's edges. Instead there could simply be some space left between the upper and lower ends of the swiping area and the edges of the display.

When we already talk about this I recommend to compare the swipe controls of Zapp to those other media apps, just for inspiration. E.g. [NewPipe](https://newpipe.net/) does not control brightness and audio volume in absolute values but in relative values. So you can e.g. repentantly swipe the same area of the screen to raise the volume up swipe by swipe, step by step. VLC for android does it the same way. NewPipe displays the current value as the contour of a circle in the middle of the screen, but I think that does not make difference in control, maybe in UX. VLC does display a bar at the side to visualize the current setting. What I like about that is that it also displays a percentage value. I always like precision. The side bar of Zapp can be seen better than that of VLC because of its color.

I hope that a change of the swipe gesture will be considered, for which I described a probably relatively small effort approach and a probably higher effort approach. 

Thanks in advance. :)

Update:
Sry, I did not see [this issue](https://github.com/mediathekview/zapp/issues/312) before posting, which is related. Although it is not the same.

**Comment by cemrich** [comment]
Thank you very much for your detailed feedback! I am unsure about relative adjustments, but narrowing down the swipe erea should be straight forward :)

**Comment by justf0rfun** [comment]
That¨s okay for me. Maybe you remember this proposal when someday the UI / UX of the app is revised or at least the relevant parts. ;)

**Comment by cemrich** [comment]
I think I found a nice solution in v7.0.4 for the time being. 

Please feel free to test it and give some feedback :)

**Comment by justf0rfun** [comment]
When I download the apk build from github"s download page from tag 7.0.4, can I install and use it beside the stable install of Zapp from F-Droid or do I better have to uninstall that latter first to avoid conflicts?

**Comment by justf0rfun** [comment]
I uninstalled zapp, downloaded and installed the v7.0.4 apk. AFAICS the following details have changed:

1. The audio volume and brightness slider both display the set value in per cent.
2. I don't have to slide my finger to the outer edge of the display any more to set volume / brightness to minimum / maximum. Instead the extrema values are reached before my finger reaches the display's boundary. This is nice because it is easier to set low  or minimum values. 
The slider bars that visualize the current value still reaches from the bottom edge of the display to the upper edge in case the maximum value is set. It might be considered to add a padding to the bars, too, so that it corresponds to the area where is slider actually change values. That is under the assumption that the slider sets the values linear / proportionally to the finger movement of the slider. It guess the mapping isn't exponential, he? :D That said, it is only cosmetic and I can't judge which would be better UX wise.

Is that the intended behavior? 

Thanks for your work. :)

**Comment by cemrich** [comment]
> Is that the intended behavior?

Yes. This was a happy little coding accident, but I quite like the UX. And it should solve the issues mentioned above.

**Comment by cemrich** [comment]
The fix is released in version 7.0.4. Please comment or reopen if needed.
