### ISSUE TITLE
Feature: Quality Setting for Unmetered Networks

### ISSUE THREAD

**Issue by svoop** [mediathekview/zapp#318]
Would it be very hard to add a quality dropdown for unmetered networks along the existing one for metered networks?

In my case, I'm often nomadic and to keep the config overhead down, I'm using the same wifi SSID for my home router (unmetered) as well as when sharing my 4G/5G mobile internet (metered). It would be nice if I could always use the lowest quality setting for live streaming which is sufficient in either environment.

Also, low quality means less data means less energy means less CO2, so if you don't really need hires, it would be nice to always go lores. (With this in mind, an "audio only" option in the quality dropdown would be great as well, but I'm not sure that's actually supported upstream.)

Last but not least: Thanks a bunch for Zapp!!

**Comment by cemrich** [comment]
Thank you very much for your suggestion!

ExoPlayer is (at least for the live streams) very smart about quality selection, so I will not tell it what to do for unmetered networks. Quality selection as it is right now is already a wonky feature and I really try not to complicate it any further.
