### ISSUE TITLE
Feature: Monochrome icon

### ISSUE THREAD

**Issue by neunzehnachtneun** [mediathekview/zapp#320]
Android 13 was released a few weeks ago. Icons should follow Material You since then.

To implement material icons, see: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
Signal, VLC, OrganicMaps and other apps already support this feature, so I think it would be great if zapp would support it too.

**Comment by cemrich** [comment]
Thank you very much for this suggestion!

**Comment by eUgEntOptIc44** [comment]
@neunzehnachtneun as I take it this seems to be integrated by be13231

**Comment by cemrich** [comment]
Yes, next release will have a nice monochrome icon!

**Comment by cemrich** [comment]
This issue is fixed with version 8.0.0
