### ISSUE TITLE
List downloads recoverable?

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#321]
My smartphone said goodbye the day before yesterday. :-(

The ZAPP app contained numerous aborted downloads. Is there a chance to import the list back onto the new device later, provided that the data recovery via a professional service provider is successful?

Thanks

**Comment by WebworkrNet** [comment]
Data recovery is unlikely now that I know the price ranges :-(, but I would still be interested in the answer.

**Comment by cemrich** [comment]
Zapp saves all its data in a sqlite database. It might be possible (on rooted devices) to obtain this database and somehow copy it over to a new device - but this is a rather hacky aproach. Zapp is opting in for Googles backup automatism, if you enabled it for your device - this should also work for other backup solutions like SeedVault.

**Comment by WebworkrNet** [comment]
Could the current download list (title, download path) be saved in the future in such a way that they could be imported again via Google Drive if required in a user-friendly way and without root rights?

Alternatively, I could also imagine an export/import function for the download list.

**Comment by WebworkrNet** [comment]
After first setting up my new device using a new Google account, I have now reset the device to the factory settings once again and I am currently setting up the smartphone again under the original Google ID. Fortunately, the failed downloads reappeared when I reinstalled Zapp. I had no longer expected this. I assume that it is complete, because it is very extensive. :-)

**Comment by cemrich** [comment]
Great backup :D

The download status is saved inside the database, so failed downloads will be becked up too.

**Comment by WebworkrNet** [comment]
I currently see that the data backup of the app data and thus a possibility of recovery is not sufficiently guaranteed, as shown (again) in issue "First crash, then "my programs" empty #466". 

According to current knowledge:
1. A restore via the Android Google backup is not possible in a dedicated way. A complete restore is required, which is probably only possible after resetting the device to factory settings.
2. The native Android backup of the app is outdated in the case of #466, although the data backup was made promptly.

**In this context, I would ask you to think again about an import/export function.** 

In my opinion, this is not a concern for intensive users, but affects all users. When changing devices, the native backup may still be sufficient, as was fortunately finally demonstrated in November 2022. However, if only the ZAPP app has problems, the current backup is not the right tool for recovery in my opinion because it is too rough. Problems with the app can affect any user. As a heavy user, I certainly experience problems more frequently than others. But that doesn't mean that they can't happen to others. The probability is just significantly higher for me than for others.
