### ISSUE TITLE
Invalid timestamp in search bottom sheet

### ISSUE THREAD

**Issue by eUgEntOptIc44** [mediathekview/zapp#322]
I really love this app 👍. The general UX is way better than any of the 'official' apps or websites for the Mediatheken.

While searching with zapp I experienced the following bug:
![Screenshot_20220930_194556_Zapp](https://user-images.githubusercontent.com/90517741/193335241-bbf4e825-4f30-455c-9a06-810e808946b2.png)

There's a invalid timestamp at the top of the search bottom sheet. Also the number of search results in the same string is invalid. It's always zero. This bug might have been already reported. However I couldn't find anything on this issue so far.

**Comment by cemrich** [comment]
Thank you very much for reporting! This is a known issue (#314) and will be fixed in one of the next releases.
