### ISSUE TITLE
Screenshots: 404

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#324]
https://github.com/mediathekview/zapp

Looks like deposited screenshots are not found.

![Screenshot_20221014-201742_Fennec.jpg](https://user-images.githubusercontent.com/43509007/195914871-eb340846-a60b-4312-af9f-0563930efa36.jpg)
![Screenshot_20221014-201800_Fennec.jpg](https://user-images.githubusercontent.com/43509007/195914891-ef472d2d-d7a3-4e0c-854b-973f80f79551.jpg)

**Comment by cemrich** [comment]
Thanks for your report!

It's fixed. Screenshots are still slighly outdated though.
