### ISSUE TITLE
Question: Is there a way to add channels without having to compile the whole app?

### ISSUE THREAD

**Issue by thornySoap** [mediathekview/zapp#333]
I tried to edit channelInfoList.json without any effect.
Sorry if this sounds like a stupid question.

**Comment by cemrich** [comment]
Zapp fetches updated channel infos from https://api.zapp.mediathekview.de/v1/channelInfoList, which override the local channels. You can let this url (strings/config.xml) poitn to another url and serve the channels you like - but I doubt this is possible without recompiling.

Compiling should not be too difficult however.

**Comment by thornySoap** [comment]
Ok thanks
