### ISSUE TITLE
Adjust size of overlay player. 

### ISSUE THREAD

**Issue by Ver-Nunft** [mediathekview/zapp#334]
Newpipe let's you change the size of the overlay player, unfortunately Zapp doesn't despite being a rather small window.

**Comment by cemrich** [comment]
Thank you very much for your feedback!

Zapp uses the Androids default Picture-inPicture window, which is quite powerful:

> Users can drag the PiP window to another location. Starting in Android 12, users can also:
> - Single-tap the window to display a full-screen toggle, a close button, a settings button, and custom actions provided by your app (for example, play controls).
> - Double-tap the window to toggle between the current PiP size and maximum PiP size.
> - Stash the window by dragging it to the left or right edge. To unstash the window, either tap the visible part of the stashed window or drag it out.
> - Resize the PiP window using pinch-to-zoom.

I will not backport this functionality to older Android versions, as it would result in too much code to maintain.
