### ISSUE TITLE
Media library tab: Display download status

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#342]
In the "Media Library" tab, I can already see in the overview if a download was successful. However, downloads that are in progress or have been interrupted are only visible without calling up the detailed view of a programme. Appropriate icons would be helpful. 
In my opinion, this is particularly relevant for series.
Thank you

**Comment by cemrich** [comment]
I don't understand. There are download progress indicators, error- and success icons on every screen and list item.  On which view exactly do you miss an indicator?

**Comment by WebworkrNet** [comment]
The feature request has been resolved with the release of version 8.0.0 (63). Many thanks for the new features :-)

**Comment by cemrich** [comment]
Nice! There has been a version confusion :)

**Comment by WebworkrNet** [comment]
When I opened the ticket, version 8.0.0 (63) was not yet available for download. Consequently, I did not know the new functions yet. :-)
