### ISSUE TITLE
Live stream quality very bad

### ISSUE THREAD

**Issue by Andreas-ddl** [mediathekview/zapp#346]
Zapp version: 8.0.0 tested on Android 10 with Lenova Tablet Tab M10 FHD Plus.

Seems to affect all live streams and to be easy to reproduce with different android versions or HW.

The problem is:

- the picture isn't sharp
- picture and sound aren't synchronous

Version 7.0.4 doesn't show the problems.

**Comment by cemrich** [comment]
I cannot reproduce this issue on my test devices. Are you by any chance connected to a metered network?

**Comment by Andreas-ddl** [comment]
No, I used always wlan. With Smartphones and Android 9, 11, 12 or 13 I couldn't reproduce it neither. My other tablets unfortunately use so old os- versions, that they aren't even supported.

**Comment by cemrich** [comment]
This smells like a network stack issue. I'll try to reproduce this on an emulator.

**Comment by cemrich** [comment]
Das Erste is looking very blurry and most definetly not HD on the Android 10 emulator. ZDF and Arte are looking file.

**Comment by cemrich** [comment]
Note to self: Switching back to DefaultDataSource instead of OkHttpDataSource in ExoPlayer does not resolve this issue.

**Comment by cemrich** [comment]
I can confirm that this issue did not exist in version 7.0.4. I updated exoplayer from 2.17.1 to 2.18.2. Further experimentation shows, that the issue only occurs with exoplayer 2.18.2 (not 2.18.1 or below). So I would assume, that this is a bug in the library. As for now there is now newer version available.

**Comment by cemrich** [comment]
I passed this issue to google.

**Comment by cemrich** [comment]
@Andreas-ddl Is there any other device you can reproduce this issue with? If not, this may be a device specific system bug of the Lenova Tablet, underreporting the framerate it is able to play back.

**Comment by Andreas-ddl** [comment]
No, cannot reproduce it with other devices. But also is only item with Android 10.

I also made some more tests. I can confirm that it doesn't concern all channels but definitely "ARD".

**Comment by cemrich** [comment]
@Andreas-ddl Thank you very much for testing! I'll treat this as a hardware bug for the time beeing. The behaviour of exo player seems to be "correct" (at least to spec). This is nothing that should be fixed by Zapp. Sorry!

**Comment by neustrelitzer** [comment]
Seit v8.0.x nutze ich für Das Erste nicht mehr Zapp, sondern nur noch die originale Mediathek-App der ARD. Zapp bietet mir bei diesem Kanal maximal HD, meist jedoch weniger. Die offizielle App zeigt die Sendungen problemlos in FHD an. Außerdem kann man in letzterer App die Qualität einstellen, also erzwingen.

**Comment by cemrich** [comment]
@neustrelitzer Danke für den Hinweis! Zapp sollte den ARD-Stream eigentlich in FHD anzeigen können, wenn das Gerät den Codec, die Framerate und die Videogröße unterstützt. Wir schränken da nichts ein.

**Comment by neustrelitzer** [comment]
Nachdem die Entwickler der ARD-App es nach Monaten endlich hinbekommen hatten, die Videos auch auf einem _Samsung Galaxy Tab A8 Wi-Fi (SM-X200)_ in FHD anzeigen zu lassen und man dies zudem dort erzwingen kann, habe ich den direkten Vergleich.
Getestet hatte ich das vergangene Woche und am Wochenende mehrmals mit der Sendung _"Wer weiß denn sowas?"_. Sowohl die Vorabend-Episoden als auch die XXL-Sendung am Samstag Abend waren im Livestream mit Zapp einfach grauselig anzuschauen und unscharf. Ein Wechsel zur App _ARD Mediathek_ brachte eine deutliche Verbesserung und ein gestochen scharfes Bild.
Anmerken muss ich, dass meine Internet-Verbindung über das WLAN recht schmalbandig ist. Ich werde das noch mit einer Mobilfunk-Verbindung (Tethering) testen, wenn das Datenvolumen es zulässt.

**Comment by cemrich** [comment]
> Anmerken muss ich, dass meine Internet-Verbindung über das WLAN recht schmalbandig ist.

Es kann sein, dass ExoPlayer es deswegen nicht zulässt. Es kann aber auch der gleich "Bug" sein, wie bei dem Gerät oben. Ich hoffe, dass die Probleme mit dem nächsten Release von ExoPlayer etwas nachlassen.
