### ISSUE TITLE
Since version 8.0.0 the videos from the Mediathek section stutter

### ISSUE THREAD

**Issue by Monstanner** [mediathekview/zapp#350]
## Which channel does not work correctly?

As described above, the videos stutter in the Mediathek section. The livestreams are running so far without stuttering. I have tested all newer versions (8.0.0, 8.1.0, 8.2.0), but the problem persists.

My hardware and software:
Device: Nokia 6.1
OS: Android 10 Vanilla

## What is the problem?
- [ ] does not load at all
- [ ] shows always the same looping content
- [X] performance problem (stuttering or other)
- [ ] other problem (add description)

**Comment by cemrich** [comment]
Thank you very much for your feedback!

This is most likely a problem with the updated version of exoplayer and your device. Do you have similar issues with other video apps? Does it help to download the show? Are all videos stuttering?

**Comment by cemrich** [comment]
Thanks for the clarification!

[Xtra ](https://github.com/crackededed/Xtra) is using the same version of Exoplayer, so I suspect an issue on their side. The is a similar issue open at Xtra: https://github.com/crackededed/Xtra/issues/197 Can you confirm this bug on your device? Also, there is a solution posted as response to this issue. Does it fix the issue for you?

**Comment by Monstanner** [comment]
> Thanks for the clarification!
> 
> [Xtra ](https://github.com/crackededed/Xtra) is using the same version of Exoplayer, so I suspect an issue on their side. The is a similar issue open at Xtra: [crackededed/Xtra#197](https://github.com/crackededed/Xtra/issues/197) Can you confirm this bug on your device? Also, there is a solution posted as response to this issue. Does it fix the issue for you?

Yes, stuttering is no longer present in Xtra due to this option.

**Comment by OddSobriquet** [comment]
The problem also applies to live streams, not just Mediathek.

https://user-images.githubusercontent.com/72888738/212301455-95a0d822-2778-48d0-a2e8-fc6504902ae7.mp4

**Comment by Monstanner** [comment]
> The problem also applies to live streams, not just Mediathek.
> 31905.mp4

I checked it again and you're right. I had intended, through your comment, to make a list of the stations that stutter. But then I noticed at the mdr that only some programs stutter and some do not. So it can also have something to do with the quality of the image and how much happens in the image. It stuttered on a music show, but not on a talk show. Both programs had a good picture quality but the music show was much more going on in the picture. That's why I think the list is pointless, as it varies. I hope that the solution from Xtra can be adopted. As a workaround for the Mediathek, you share the video with an app like VLC.

**Comment by OddSobriquet** [comment]
>So it can also have something to do with the quality of the image and how much happens in the image.

I can imagine it being connected to stream (live or locally stored) quality.
I would've tried using a lower stream quality to see if the problem persists, but unfortunately Zapp doesn't offer a setting to change stream quality / resolution (neither in settings nor in the player directly [little cog wheel as in Xtra, Newpipe]). I already ran out of data this month so...

I can attempt downloading a programme using low resolution option but that won't be happening until after the week end.

**Comment by cemrich** [comment]
Thank you very much for debugging this!

This seems to be an issue with exoplayer. They changed something in the mechanics of which decoder is selected between versions 2.18.1 and 2.18.2 which seems to cause some devices to choose a software decoder. See https://github.com/google/ExoPlayer/issues/10808 for a similar issue.

Xtra works around this issue by optionally forcing a hardware decoder in the settings. I would like to avoid this for Zapp. I will wait for the next Exoplayer update - than we will see, if this issue is fixed.

**Comment by Spielmops** [comment]
The problem seems to be the coding: often H265 is used for streams, regardless if live or Mediathek. Together with the resolution Full-HD it is something not every device is able to play fluently. 
For paid networks there is a switch for lower quality and if I use that (goto settings/wifi/my-wifi, set it do paid network), I can play the file without issue. The solution could be a switch for lower quality everywhere.

Spielmops

**Comment by OddSobriquet** [comment]
Confirms my suspicion. As mentioned: in Xtra switching to 480 the stutters and choppy playback disappeared.

I think a quality setting hidden behind the cog (where audio channel and playback speed are located) would be the "easiest" solution.

I wouldn't remove the quality preferences for metered/ unmetered connections from the main settings page completely but I would implement it as a preference (a default go to) which can be overridden at any time using cog>quality when watching a stream.

**Comment by ChristianCiach** [comment]
For what it's worth, I see the same issue on my new device "Lenovo m10 plus 3rd gen" that I bought for my mother. The decide is on Android 12 (all updates applied) is uses the Mediatek G80 chipset.

The first few seconds of a stream are usually fine, but then it switches to HD and it immediately becomes choppy.

Are there any workarounds for the time being?

**Comment by ChristianCiach** [comment]
*Appently updating exoplayer to 2.18.3 fixes the issue: https://github.com/crackededed/Xtra/issues/197#issuecomment-1440595715

As I can see, Zapp is still using 2.18.2, so an update may be worth a shot.

**Comment by Monstanner** [comment]
It looks like it's fixed with version 8.3.0 / 8.3.1. At least on my smartphone. Thanks for fixing. However, I don't close the issue because I don't know if there are still problems with other users' smartphones.

**Comment by ChristianCiach** [comment]
Can confirm that it is fixed for the MediaTek Helios based device of my mother. Thanks!

**Comment by Der-Flip** [comment]
Kinda forgot about this one, but yes Redmi9C with android 10 looks smooth as well

**Comment by cemrich** [comment]
Nice! 

Thank you all for helping. Thanks to you, a lot of people are getting stutter free videos in a whole lot of apps :)
