### ISSUE TITLE
Multiple listings in media library

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#352]
Under certain circumstances, programmes are shown more than once in the Media Library. I am explicitly not talking about when the ARD and ZDF broadcasting groups have posted them several times (example ARD/NDR, ZDF/3sat), but about one and the same programme. This can be determined by setting a bookmark.

Example:
Filtering for the term "Retour".
The programme "Landesschau Baden-Württemberg - Michele und Ingo Morlock handeln mit Retouren von Online-Händlern" (SWR) appears twice in the filtered list.

However, if I search explicitly for the title, the programme is only shown once (SWR).

Edit:
**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 13
**ZAPP**: 8.2.0 (65)

**Comment by WebworkrNet** [comment]
@cemrich 
The release notes for version 8.5.2 mention that duplicates have been removed when scrolling in the media library list. Does this fix refer to this issue?

**Comment by cemrich** [comment]
> Does this fix refer to this issue?

Yes, most likely I smashed this bug :) Please feel free to open a new issue if you should encounter this bug again.
