### ISSUE TITLE
Replace relative time by actual time

### ISSUE THREAD

**Issue by defini-tiv** [mediathekview/zapp#355]
# Issue:
The playback time in the corner of the player (1:59:46 / 2:00:00)
has many digits for few information. The 2 hours are almost arbitrary because you see them way more often than you care about the maximal buffering time. If users want to know if they can go back 2,5 h, they will try in the timeline and see that 2h is the maximum. The "2h minus delay" timestamp is unecessary big, because you care about the delay which is <10min in most cases.(In the case above it would be "-14" instead of "1:59:46")

# Suggestion:
Show the absolute time instead e.g. "20:03:07 / 20:03:31". This is more useful to see the current time in the player next to the time of the brodcasted stream.

# Alterenatives:
- Just the delay: -0:0:14.
- Delay + Absolute time: 20:03:31 - 0:0:14.

**Comment by cemrich** [comment]
Thank you very much for this suggestion!

This behaviour is the default behaviour of exoplayer, the videoplayer Zapp is using. Changing this would cause much more code to maintain for minimal UX improvement.
