### ISSUE TITLE
[feature request] preselection of the app start view

### ISSUE THREAD

**Issue by atomphil** [mediathekview/zapp#357]
I never use Zapp to watch live streams, but exclusively as a Mediathek player. It is therefore inconvenient for me that the app always starts in the livestream view. It would be nicer if you could set the start view in the settings and then it starts directly with the Mediathek tab ([or the tab with the search favourites ;-) ](https://github.com/mediathekview/zapp/issues/356)).

**Comment by return42** [comment]
> It is therefore inconvenient that the app always starts in the livestream view.

my 2cent: me and the users I know mainly use ZAPP (as the name said) to zapp from one live stream to the next .. a substitute for the TV and its remote control when they are not available :-)

BTW: thanks a lot to the ZAPP team :+1:

**Comment by atomphil** [comment]
> my 2cent: me and the users I know mainly use ZAPP (as the name said) to zapp from one live stream to the next .. a substitute for the TV and its remote control when they are not available :-)

so it would be nice to have the choice in the settings to adapt the app to the different user requirements.

**Comment by cemrich** [comment]
Thanks to @Bryno this will be available in the next release.

**Comment by atomphil** [comment]
Great! Thank you @bnyro 👍

**Comment by cemrich** [comment]
This feature has been added in 8.3.0
