### ISSUE TITLE
Cancel / delete failed downloads

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#365]
In the detailed view of a programme, a failed download cannot currently be cancelled or deleted. It is only possible to restart the download. To do this, it is necessary to switch to the view "My programmes" or "Downloads". This is somewhat cumbersome from the user's point of view.

**Comment by cemrich** [comment]
There is a menu item to delete the download in details view. It is hidden behind the overflow menu (three vertical dots). Additionally, the partially downloaded file is deleted automatically on final failure.

Please commend or reopen, if you have any more issues with deleting failed downloads.

**Comment by WebworkrNet** [comment]
Thanks for the explanation, found it. :-)
