### ISSUE TITLE
Show button for detailed info about current emission in "Live" view

### ISSUE THREAD

**Issue by SehLax** [mediathekview/zapp#368]
In the "mediathek" view, clicking on an entry first opens the text, which is nice to understand if I want to watch this.
In the "Live" view, clicking a station (and emission) directly opens the stream, which is nice for "zapping", but I would very often like to read first the topic, guests etc. of the emission before opening it and being overwhelmed by video and sound :D (and then having to turn my device, and pressing "i" again and then sliding the info box up)
Could you imagine to add a little "i" for information button at the side, or maybe show the descriptive text when you press long on an emission? Would love it, so probably others too?

**Comment by cemrich** [comment]
Thanks a lot for your feedback. This feature has been implemented in version 8.4.0!
