### ISSUE TITLE
[Suggestion] Add thumbnails

### ISSUE THREAD

**Issue by TechD123** [mediathekview/zapp#376]
Would it be possible to include pictures/thumbnails for shows in the Mediathek? As I understand, you're scraping the websites for info, so I would naïvely assume thumbnails are possible too ;)

I'm suggesting this because the Mediathek listing feels a bit cluttered without any visual cues. I'm imagining having thumbnails left of each episode listing, with the current info (title, duration, channel, date of publication) to the right of the image.

If thumbnails aren't possible at all, maybe even just adding icons (in color in light mode, black/white in dark mode) of the corresponding channel in place of the text (e.g. instead of the letters ZDF underneath the title, the logo is used) would add some easy visual orientation.

If thumbnails are mostly possible, with some failures due to the nature of scraping, we could fallback to filling the thumbnail square with a placeholder, possibly the channel logos as described above.

Combining this with #356 should make for an even more awesome user experience (I'm assuming that the most intuitive option, series -> episode, isn't implemented because it's not possible to group episodes reliably using scraping).

Thank you for contributing free software!

**Comment by return42** [comment]
> As I understand, you're scraping the websites for info, so I would naïvely assume thumbnails are possible too ;)

AFAIK the infos are read from MediathekViewWEB (MVW) ..

https://github.com/mediathekview/zapp/blob/36919ba4aa8024213214f23a34cdf4bf0562a9d7/app/src/main/res/values/config.xml#L5

```
curl 'https://mediathekviewweb.de/api/query' -H 'content-type: text/plain' --data '{"queries":[{"fields":["topic"],"query":"#Livestream"},{"fields":["title"],"query":"+Livestream"}],"sortOrder":"desc","future":true,"offset":0,"size":2}' | json_pp
...
```

Sadly MVW does not scrap thumbnails for the items:

```JSON
{
   "err" : null,
   "result" : {
      "queryInfo" : {
         "filmlisteTimestamp" : "1692700200",
         "resultCount" : 2,
         "searchEngineTime" : "2.05",
         "totalResults" : 45
      },
      "results" : [
         {
            "channel" : "DW",
            "description" : "",
            "duration" : "",
            "filmlisteTimestamp" : "1671312060",
            "id" : "8+BoYmnJMAnL6xM+o6ksM5QlbVe+p9K5KNoqI2mq6q8=",
            "size" : null,
            "timestamp" : 0,
            "title" : "DW Livestream",
            "topic" : "Livestream",
            "url_subtitle" : "",
            "url_video" : "https://dwamdstream111.akamaized.net/hls/live/2017972/dwstream111/index.m3u8",
            "url_video_hd" : "",
            "url_video_low" : "",
            "url_website" : "https://www.dw.com"
         },
         {
            "channel" : "HR",
            "description" : "",
            "duration" : "",
            "filmlisteTimestamp" : "1671312060",
            "id" : "z1ygSQCgSHQsw+nNXmfs+hzy3/6qT9/KMKjofz8kul0=",
            "size" : null,
            "timestamp" : 0,
            "title" : "HR Livestream",
            "topic" : "Livestream",
            "url_subtitle" : "",
            "url_video" : "https://hrhls.akamaized.net/hls/live/2024525/hrhls/master.m3u8",
            "url_video_hd" : "",
            "url_video_low" : "",
            "url_website" : "https://www.ardmediathek.de/live/Y3JpZDovL2hyLmRlL0xpdmVzdHJlYW0tSFI/"
         }
      ]
   }
}
```

**Comment by TechD123** [comment]
Aww, that's a shame. I just checked and it looks like the devs [weren't interested](https://github.com/mediathekview/mediathekviewweb/issues/167) in implementing it until now. Have asked for an update.

**Comment by cemrich** [comment]
Thank you very much for the suggestion! 

Thumbnails would be very nice, but currently are not provided by the mediathekviewweb api. Also, displaying them in every client would cause quite a performance impact on the mediathek servers - so this is a feature which most likely will not be implemented.

**Comment by cemrich** [comment]
> If thumbnails aren't possible at all, maybe even just adding icons (in color in light mode, black/white in dark mode) of the corresponding channel in place of the text (e.g. instead of the letters ZDF underneath the title, the logo is used) would add some easy visual orientation.

I already tried this ;) It adds a aweful lot of visual clutter with minimal benefit for the user.
