### ISSUE TITLE
No connection to Mediathek

### ISSUE THREAD

**Issue by Discostu36** [mediathekview/zapp#381]
Since a few hours the app can't connect to the Media center anymore.

![Screenshot_20231005-214517_1](https://github.com/mediathekview/zapp/assets/30999326/0369ea57-e353-46b7-bc86-6b984a4dc041)

Live streams and "My Shows" still work.

Zapp 8.3.2
Abdroid 12
Fairphone 4

**Comment by dagofr01** [comment]
Identical setup for me - no problem. 
Check your network setup. VPN related apps ?  Blokada ?  Reboot your phone ?
Also your ISP may have an issue only relevant for certain destinations. So I would just wait for a bit. :-)

**Comment by Discostu36** [comment]
I did deactivate NetGuard and reboot my phone before opening the issue. But now the error is also gone for me, some temporary hickup 🤷🏽‍♂️
