### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [mediathekview/zapp#415]
It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by Bnyro** [comment]
This should rather be proposed to the whole MediathekView project instead, it's certainly not a good idea to split the source code across different platforms.

**Comment by alex1702** [comment]
Not currently planned. The effort is disproportionate to the benefit. All developers here in the team have github and can live with working on a platform that is not itself open source.
For some repo's there are replications on gitlab and on a private gitlab instance.
