### ISSUE TITLE
Opening external links: ZDF media library

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#416]
Samsung Galaxy A13 5G (SM-A136B)
Android 13
ZAPP 8.4.0

Parallel to ZAPP, I also installed the ZDF media library (https://play.google.com/store/apps/details?id=com.zdf.android.mediathek&hl=de). Links to the media library of the Zweites Deutsches Fernsehen are opened within ZAPP contrary to the usual behavior. Other destinations are opened in a standardized manner either in the corresponding media library app or in the standard browser.

![Screenshot_20240116_125502_Zapp](https://github.com/mediathekview/zapp/assets/43509007/6474f3bf-4496-4cfd-bac6-9c6bb4c2a053)

![Screenshot_20240116_125529_ZDFmediathek](https://github.com/mediathekview/zapp/assets/43509007/9551f979-6ce0-466e-87ec-ee5910050ce4)

![Screenshot_20240116_125543_One UI Home](https://github.com/mediathekview/zapp/assets/43509007/f8bb5857-629f-4183-ba1a-8838a1fc10d9)

**Comment by cemrich** [comment]
Thanks for reporting!

I would suggest, this is intended behaviour of the Android system. Zapp is using a very, very pain "please system, view this url" intent - nothing fancy here. The ZDF app is most likely registering for the "https://zdf.de/" url scheme and responding to this system call.

Why browsers and the ZDF behave differently regarding the app stack, I cannot tell. But there is nothing Zapp can change whithout breaking other things.

**Comment by WebworkrNet** [comment]
If I uninstall the ZDF media library, ZDF links open externally in the default browser as expected.
However, the phenomenon occurs again when reinstalled. A temporary problem can probably be ruled out.

Who should I contact to get this resolved? Samsung or ZDF?

**Comment by cemrich** [comment]
This can only be fixed by the ZDF app - but like I said: this is intended behaviour.

**Comment by WebworkrNet** [comment]
Desired behavior? In what way?

What is the best way to give feedback to ZDF, i.e. in terms of content? Is there anything technical I should point out regarding Android? Should I mention ZAPP or not?

**Comment by return42** [comment]
> Desired behavior? In what way?

When you ..

> However, the phenomenon occurs again when reinstalled.

...

> The ZDF app is most likely registering for the "https://zdf.de/" url scheme and responding to this system call.

> What is the best way to give feedback to ZDF

They should not register their App for the "https://zdf.de/" url scheme .. 

>  Should I mention ZAPP or not?

its not related to ZAPP .. all Apps that want to open a "https://zdf.de/" url will be handled by the ZDF App .. 

> Desired behavior? In what way?

it is the behavior desired by the ZDF app.

If won't this behavior, you can not install the ZDF App.
