### ISSUE TITLE
Card file corpse: "Das Geheimnis des Hundeblicks"

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#417]
There are entries in the database without download links or playlist URLs:

**Wissen vor acht — Natur
Das Geheimnis des Hundeblicks**

Please clean database.

_The request is probably placed incorrectly at this point, please move it if necessary._

Thanks

**Comment by cemrich** [comment]
Thanks for your report!

The data seems to be correct. I don't know why exactly, but the urls are m3u8 playlists (like for all ORF shows). They cannot be downloaded but playback works just fine.
