### ISSUE TITLE
Einstellung "Dynamische Farben" wird nicht übernommen.

### ISSUE THREAD

**Issue by lericony02** [mediathekview/zapp#429]
Ich habe die Einstellung _Dynamische Farben_ interessehalber deaktiviert.
Wenn ich diese nun wieder aktivieren möchte, tut sich nichts. Es bleibt deaktiviert. Selbst eine vollständige Neuinstallation der App bringt keine Besserung.

Gerät: Samsung Galaxy S20 FE 5G (Android 13)

Update: Die Einstellung wurde nach mehreren Versuchen plötzlich übernommen, ein testweises Deaktivieren war allerdings nicht direkt möglich.

**Comment by cemrich** [comment]
Vielen Dank für die Rückmeldung!

Ich kann das Problem in der Version 8.5.0 und Android 14 bestätigen.

**Comment by cemrich** [comment]
This is a funny one. The bug does only occur on some devices (Pixel 7) and only in release builds. It cannot be reproduces on emulators or debug builds.

I suspect a timing issue.

**Comment by Bnyro** [comment]
Ich kann es zwar nicht testen weil bei mir auf Android 14 alles funktioniert, aber ich erinnere mich daran dass man 
```kotlin
DynamicColors.applyToActivitiesIfAvailable(this) 
```
https://github.com/mediathekview/zapp/blob/998acf90b170de56d4d54b553644726f8f56c44c/app/src/main/java/de/christinecoenen/code/zapp/app/ZappApplicationBase.kt#L58-L64
vor `super.onCreate()` aufrufen muss.

**Comment by cemrich** [comment]
Der Fehler wird in Version 8.5.1 behoben sein. Es war ein Timing-Issue in Release-Builds: Zapp hat sich neu gestartet, bevor das neue Settings sauber abgespeichert werden konnte.
