### ISSUE TITLE
Live stream: HTML character entities in programme titles

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#439]
In this example, double inverted commas in programme titles are not displayed correctly. Instead of `"`, `&quot;` is displayed.

![Screenshot_20240719_223413_Zapp](https://github.com/user-attachments/assets/7eed031d-b3b6-4a0c-adb0-4fc2528ddd5f)

**Comment by cemrich** [comment]
This should most likely be handeled inside the program info backend api...

**Comment by WebworkrNet** [comment]
Thanks for fixing this in release [8.5.3](https://github.com/mediathekview/zapp/releases/tag/v8.5.3).
