### ISSUE TITLE
feature request: optional hide content with a future date in Mediathek list

### ISSUE THREAD

**Issue by tusch001** [mediathekview/zapp#441]
Many videos in the mediathek view have a future date assigned. Probably not intentional but they appear at the top of the list. For my personal use I'm not interested eg for a broadcast in 2027 but would like to see what I missed the last few days in TV. For this I have to scroll down about 100 entries. It would be nice to hide all entries with a future date eg with a toggle in settings.
Thanks

**Comment by cemrich** [comment]
Thank you very much for your feedback! This is indeed a duplicate - please see the linked issue above.
