### ISSUE TITLE
Zapp app probleme Firetv

### ISSUE THREAD

**Issue by 3dmax1979** [mediathekview/zapp#442]
App lässt sich unter firetv nicht installieren. Installation startet ist aber nicht vollständig. Firetv Cube zweite Generation. Android 9 32bit arm7.

**Comment by PYCODR** [comment]
same here on FireStick 4K

**Comment by 3dmax1979** [comment]
Problem hatg sich erledigt. Nach dem neuesten Updates und Cache von einigen Apps Löschen ist Installation wieder möglich.
