### ISSUE TITLE
Untertitel herunterladen

### ISSUE THREAD

**Issue by Discostu36** [mediathekview/zapp#443]
Es scheint bisher keine Möglichkeit zu geben, Untertitel herunterzuladen. Über das Feature würde ich mich freuen, um die Untertitel auch außerhalb der App nutzen zu können.

**Comment by 3dmax1979** [comment]
Geht mit extwas Handarbeit auch jetzt schon. Über die WebVersion https://mediathekviewweb.de/. Oben einen Suchbegriff eingeben. Rechts auf Video gehen. Dort werden die Videos in drei Varianten angezeigt. Wenn Dort Ut Steht gibt es Untertitel für die Sendung. Können über den Link geleden werden.

**Comment by Discostu36** [comment]
Ja, das ist ja mehr ein Workaround, aber ich hätte es gerne in der App, wenn möglich 😊

**Comment by cemrich** [comment]
Vielen Dank für das Feedback! Wir haben dieses Feature schon mit issue #213 auf den Schirm und werden dort Updates geben.
