### ISSUE TITLE
Incorrect umlaut and `ß` display

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#450]
**Steps to reproduce**
Call up a tab or a detailed view.
**Expected behaviour**
Proper character set representation
**Actual behaviour**
Umlauts and `ß` are displayed incorrectly.
**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 14, One UI-Version 6.1
**ZAPP**: 8.5.2 (72)

**Comment by WebworkrNet** [comment]
As the phenomenon has only been occurring for a few days and the last app update was some time ago, the cause is probably to be found in upstream Mediathekview or ZAPP components or at the broadcasters.

I am trying to find out whether the problem can be narrowed down to certain channels.

**Comment by WebworkrNet** [comment]
ZDF

![Screenshot_20240907_005615_Zapp](https://github.com/user-attachments/assets/d513f8a9-5a48-4a69-a3d2-d785a6015e11)
![Screenshot_20240908_190342_Zapp](https://github.com/user-attachments/assets/7817f1f2-d36d-4300-b1df-fd67486e828b)
![Screenshot_20240908_191524_Zapp](https://github.com/user-attachments/assets/d62b1a45-36ad-4d3c-9b7a-8a87ad0c0fea)

**Comment by bagbag** [comment]
Das kommt durch diesen Bug: https://github.com/nodejs/node/issues/54543

Habe natürlich genau mit der betroffnen Version zuletzt gebaut. Update ist deployed - sollte also wieder passen.

**Comment by WebworkrNet** [comment]
Phoenix live stream

![Screenshot_20240909_225309_Zapp](https://github.com/user-attachments/assets/7a0a0280-8a22-4ad9-bd70-a9316cfdae2b)

**Comment by WebworkrNet** [comment]
Will the change only affect new programs or also programs that have already been imported into the database by Mediathekview?

**Comment by cemrich** [comment]
> The cause was this bug: https://github.com/nodejs/node/issues/54543

Thanks you very much for the fix!

> Phoenix live stream

This is a separate issue.

**Comment by WebworkrNet** [comment]
> > Phoenix live stream
> 
> This is a separate issue.

@cemrich Is there already a bug report on this?
