### ISSUE TITLE
Higher Playback Speed + Persistence

### ISSUE THREAD

**Issue by JonDerThan** [mediathekview/zapp#453]
Currently, playback speed is limited to 2x. I'd like to be able to watch videos at 4x.

Also, the speed defaults to 1x when starting a Mediathek video. It would be nice if the speed defaults to the last selected one.

**Comment by cemrich** [comment]
Thank you very much for your feedback!

This is not a feature we ill implement in Zapp. We are using the default android.media Player (former ExoPlayer) and every change in its behaviour results in a lot of mainance work. I don't think that enough user are intereseted in this feature to justify this work and complexity.
