### ISSUE TITLE
Media library: Hiding channels without download option

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#460]
I would find it helpful if I could deselect channels that do not offer downloads. This currently applies to "ORF" and "SRF".

Currently it is only possible to filter for certain channels. To get the desired result, I would have to select all channels except the ones mentioned above. In addition, these filters are not permanent. I currently have to reset the settings every time I search, which is quite cumbersome.

**Comment by WebworkrNet** [comment]
As a supplement to existing feature requests:
- Blacklist/filter media library entries for certain words/strings #106
- Save search queries in the media library filter #303
- New tab with predefined media library searches #356

**Comment by cemrich** [comment]
Thanks for your feedback, but this is nothing I will implement in the near future.
