### ISSUE TITLE
Recent queries as search suggestions in mediathek list

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp#58]

**Comment by cemrich** [comment]
Postponed because I'll need a database and a possibility to delete old queries. That's too much work right now.

**Comment by SvhAdm** [comment]
maybe just add a button to save a query to a "favorites" list ?!?

**Comment by cemrich** [comment]
Developer reference: https://developer.android.com/guide/topics/search/adding-recent-query-suggestions.html

**Comment by cemrich** [comment]
This issue is fixed in v3.3.0, which will hit F-Droid in a few days. Please reopen this issue if you find any problems.

How it works: A query will be saved as soon as the Search-Button of the keyboard is pressed and can be deleted via the app settings page.
